### ISSUE TITLE
H 3.3.2 Ophalen gebiedsaanvraag geometrie in JSON is geen GeoJSON

### ISSUE THREAD

**Issue by alex3305** [kadaster/klic-win#10]
In het voorbeeld JSON response van het ophalen van een gebiedsaanvraag, wordt er de suggestie gewekt dat er met GeoJSON wordt gewerkt. Echter is dit niet het geval. Het zou met betrekking tot de open webstandaarden de voorkeur hebben om met de [GeoJSON](http://geojson.org/) standaard te werken. Tevens verhoogt dit de eenvoudigheid met betrekking tot API implementatie. Het is bij de implementatie dan namelijk mogelijk om een standaard bibliotheek te gebruiken. Voorbeelden van zulke standaard bibliotheken voor GeoJSON zijn:
- [Java, Jackson](https://github.com/bedatadriven/jackson-datatype-jts)
- [Java, Jackson](https://github.com/opendatalab-de/geojson-jackson)
- [C# (.net)](https://github.com/GeoJSON-Net/GeoJSON.Net)
- [JavaScript (Leaflet)](http://leafletjs.com/examples/geojson.html)
- [JavaScript (Google Maps)](https://developers.google.com/maps/documentation/javascript/examples/layer-data-dragndrop)
- [JavaScript (OpenLayers](http://openlayers.org/en/master/examples/geojson.html)

**Comment by martinborgman** [comment]
Het was wel als GeoJSON bedoeld, maar het lijkt er nu inderdaad niet meer op.
Wordt gecorrigeerd in de volgende versie van het document.

**Comment by martinborgman** [comment]
Is gefixed in versie 0.76
