### ISSUE TITLE
Link in Read-me van KLIC-WIN naar nieuwbrief aanmelden werkt niet

### ISSUE THREAD

**Issue by jkr-wrk** [kadaster/klic-win#101]
U kunt zich daarnaast aanmelden voor de KLIC Nieuwsbrief via https://www.kadaster.nl/nieuwsbrief over belangrijke onderwerpen en ontwikkelingen binnen het programma.

https://github.com/kadaster/klic-win

**Comment by FuatAkdeniz** [comment]
Via https://m3.mailplus.nl/genericservice/code/servlet/React?wpEncId=S3BfGPaaB7&wpMessageId=1004&userId=60615&command=viewPage&activity kan je je aanmelden.

**Comment by FuatAkdeniz** [comment]
@jkr-wrk Kan de issue gesloten worden?
