### ISSUE TITLE
BAGidAdresseerbaarObject is nu BAGid

### ISSUE THREAD

**Issue by Marijnbiekart** [kadaster/klic-win#104]
Goedemorgen, 
Even ter verificatie want ik kan hier geen openstaande issues voor vinden of voorgestelde aanpassingen.
In v1 van het IMKL is onderdeel van het type adres het attribuut "BAGidAdresseerbaarObject" waarin het BAG ID van een adres geplaatst word. 
In V2 is dit aangepast naar "BAGid" volgens mij omdat er niet alleen naar adresseerbare objecten verwezen word op andere plekken.

Logische aanpassing, mee eens, maar heb ik hier iets gemist?

**Comment by FuatAkdeniz** [comment]
Onderstaande klopt.

Het is onderdeel van issue 215, zie link onder
https://github.com/Geonovum/imkl2015-review/issues/215

**Comment by Marijnbiekart** [comment]
Bedankt! de zoekfunctie vond die niet, misschien omdat het pas in de comments over het BAG ging
