### ISSUE TITLE
Aantal tekens voor Klantreferentie is te klein

### ISSUE THREAD

**Issue by rtimmers** [kadaster/klic-win#105]
Veld Klantreferentie heeft maximaal 30 tekens. Dat is te weinig om zowel projectnaam/projectnummer als een referentie binnen het project weer te geven. 

Voorstel 1: vergroten van veld Klantreferentie naar 60 tekens
Voorstel 2: voeg veld "Project" toe aan Klic-aanvraag en zorg ervoor dat de waarde van het veld zichtbaar is voor netbeheerders. Gebruik dit veld "Project" in e-mails, Klic-overzichten tot en met facturatieoverzicht

Voorstel 1 lijkt eenvoudig te realiseren binnen bestaande kaders --> Quick fix
Voorstel 2 vereist een aanpassing van veld-definities in Klic-win

**Comment by rtimmers** [comment]
Projectnaam/Projectnummer kan een lang nummer zijn, waarbij we regelmatig een deel v/h project willen aangeven. Dit is helaas niet mogelijk met 30 tekens. In bijlage 0.jpg staat de foutmelding (met 7 extra karakters), in bijlage 1.jpg staat huidige maximum (met 6 extra karakters). In bijlage 2.jpg staat een voorbeeld van gewenste situatie (langer dan 30 karakters).

![Klic-langer-referentienummer0](https://user-images.githubusercontent.com/82505846/172383525-e74d6be6-b0d2-43fd-b0ba-3dbb2750f30d.jpg)
![Klic-langer-referentienummer1](https://user-images.githubusercontent.com/82505846/172383541-6f92ab37-482d-41b0-897b-7ea5edbf05b5.jpg)
![Klic-langer-referentienummer2](https://user-images.githubusercontent.com/82505846/172383545-32d1733d-80ce-4e22-9054-fcbd29ac294a.jpg)

**Comment by FuatAkdeniz** [comment]
TCS KLIC 25 november 2022
Met issue https://github.com/Geonovum/imkl2015-review/issues/333 zal dit een volgende versie van de upgrade geïmplementeerd worden.

Deze issue kan hiermee afgesloten worden.
