### ISSUE TITLE
KLIC-melding met strikte begeleiding: naam, telefoonnummer en mail adres van de uitvoerder verplicht maken

### ISSUE THREAD

**Issue by AndreSpijkerman** [kadaster/klic-win#108]
Vanuit de gebruikersgroep is aangegeven dat er regelmatig informatie over de uitvoerder ontbreekt bij m.n. KLIC-meldingen waarbij strikte begeleiding van toepassing is (zie onderstaande mail).

Het zou ons (Gasunie) helpen als de **naam, telefoonnummer en mail adres van de uitvoerder verplicht** wordt.

Vraag is: kan dit ingeregeld worden bij Kadaster ?

Oorspronkelijke wens:
We maken nog te vaak mee dat we halve informatie vanuit het kadaster aangeleverd krijgen bij een klic melding.
Dit is zeker van toepassing wanneer het een klic melding betreft voor striktbeheer. 
Wij moeten vanuit het loket dan actief achter de melding aan gaan bellen.
Hiervoor willen we de uitvoerder aan de lijn krijgen. 
Nu zien we te vaak dat er algemene gegevens van het bedrijf worden aangeleverd. Hierdoor is het een hele zoektocht om de juiste persoon aan de lijn te krijgen.

Het zou voor ons heel erg helpen om de naam, telefoonnummer en mail adres van de uitvoerder verplicht toe te moeten voegen. Dan hebben we meteen de juiste persoon aan de lijn.

Is dit mogelijk bij het kadaster?

**Comment by FuatAkdeniz** [comment]
TCS KLIC 16 juni
Het is een onderwerp die breed met de gehele graafsector behandeld moet worden, naar aanleiding van de WIBON evaluatie.

**Comment by FuatAkdeniz** [comment]
Met issue https://github.com/Geonovum/imkl2015-review/issues/357 zal dit opgepakt worden in de volgende versie van de KLIC-standaarden. Dit is nu een duplicaat van issue 357.

Wil je dit sluiten aub @AndreSpijkerman
