### ISSUE TITLE
readme.md bmkl2.1 URL not working

### ISSUE THREAD

**Issue by tjidde-nl** [kadaster/klic-win#109]
In the readme.md in BMKL2.1 the URL doesn't work.

It redirects to [https://github.com/kadaster/klic-win/blob/master/Toekomstige%20wijzigingen/Toelichting%20specifieke%20onderwerpen/Implementatie%20upgrade%20KLIC%20standaarden/Gewijzigde%20BMKL.md](url)

Can't find the exact document.

Thanks in advance!
//Tjidde

**Comment by JustinRoodenburg** [comment]
Hi @tjidde-nl ,

Thanks for the notification. The link is now fixed. The page where you are looking for can be found here:

[Wijzigingen/Archief/Upgrade%20KLIC%20standaarden/Gewijzigde%20BMKL.md](https://github.com/kadaster/klic-win/blob/master/Wijzigingen/Archief/Upgrade%20KLIC%20standaarden/Gewijzigde%20BMKL.md)

Kind regards,
Justin
