### ISSUE TITLE
H 3.3.2 Ophalen gebiedsaanvraag, geometrie in XML is verwarrend beschreven

### ISSUE THREAD

**Issue by alex3305** [kadaster/klic-win#11]
In het voorbeeld XML response van het ophalen van een gebiedsaanvraag worden dezelfde elementen gebruikt als in het JSON document. In de XML response zou het echter wenselijker zijn om pure GML te gebruiken, zonder extra elementen eromheen. Voorbeeld:

``` xml
<informatieGebied>
    <gml:Polygon srsName="EPSG:28992">
        <gml:outerBoundaryIs>
            <gml:LinearRing>
                <gml:coordinates>194137,465803 194136,465921 194314,465923 194315,465804 194137,465803</gml:coordinates>
            </gml:LinearRing>
        </gml:outerBoundaryIs>
    </gml:Polygon>
</informatieGebied>
```

Dit zou tevens de eenvoudigheid met betrekking tot implementatie verhogen, vanwege de mogelijkheid tot gebruik van standaard bibliotheken. Voorbeelden van zulke standaard bibliotheken voor GML zijn:
- [Java GeoTools](https://github.com/geotools/geotools)
- [Java JAXB2](https://github.com/highsource/ogc-schemas)
- [C# (.net)](Xsd2Code)
- [JavaScript (OpenLayers)](http://dev.openlayers.org/docs/files/OpenLayers/Format/GML-js.html)

**Comment by martinborgman** [comment]
Ik denk hetzelfde probleem als bij de JSON versie in het vorige issue.
De vraag die voor mij belangrijker is, is of we ook nog XML ondersteuning moeten gaan maken.

**Comment by alex3305** [comment]
Alhoewel ik niet met zekerheid kan zeggen welk formaat wij gaan gebruiken als Geodan, kan ik mijzelf indenken dat het werken met complexe datastructuren in XML eenvoudiger is dan in JSON. Dat komt mijn inziens vooral door tooling zoals [JAXB](https://jaxb.java.net/) en [xsd2code](https://xsd2code.codeplex.com/) en natuurlijk validatie tegen XML schema's. Mits er de mogelijkheid is dat de XML schema's aangeleverd worden. Dit zou eventueel iets kunnen zijn om in het achterhoofd te houden.

**Comment by martinborgman** [comment]
We gebruiken hoogst waarschijnlijk swagger.io om de interfaces mee te definiëren.

**Comment by martinborgman** [comment]
Is gefixed in versie 0.76
