### ISSUE TITLE
Feature request: Deep-link naar KLIC-View App op Android / iOS.

### ISSUE THREAD

**Issue by zwartejas** [kadaster/klic-win#111]
Na de aanvraag van een KLIC krijgt men de e-mail vanuit het kadaster met de link naar bijv. de app op de website (https://klicviewer.nl/klic-viewer/). Het zou ontzettend handig zijn om dit direct te deeplinken, bijv:

Web: https://klicviewer.nl/klic-viewer/{unieke-bestel-code}
iOS/Android: klic://view/{unieke-bestel-code} (en vervolgens aut. de app te openen)

Meer over dit onderwerp op: https://benoitpasquier.com/deep-linking-url-scheme-ios/#:~:text=Setting%20up%20URL%20Scheme,can%20create%20a%20new%20type.

**Comment by FuatAkdeniz** [comment]
Is besproken en kan afgesloten worden.
