### ISSUE TITLE
Missing extraGeometrie object in KLIC

### ISSUE THREAD

**Issue by ZbigniewOchman** [kadaster/klic-win#112]
Hi,
In KLIC 23G0519724 there is an object with GML ID: 
`nl.imkl-KL1090.Mantelbuis-33661250014742273 
`
It contains an link to extraGeometrie:
`<imkl:extraGeometrie xlink:href="nl.imkl-KL1090.ExtraGeometrie-Mantelbuis-33661250014742273"></imkl:extraGeometrie>
`
But there is no element with GML ID `nl.imkl-KL1090.ExtraGeometrie-Mantelbuis-33661250014742273` in GML. Is this correct?

**Comment by FuatAkdeniz** [comment]
You can send an email with your contact details to fuat.akdeniz@kadaster.nl

**Comment by FuatAkdeniz** [comment]
The reason why there are objects in the XML that are referenced and yet cannot be found is clipping.
Clipping of the cable and pipe based on the excavation contractor's polygon in the application.
It is an accepted phenomenon.
