### ISSUE TITLE
Missing linked objects

### ISSUE THREAD

**Issue by ZbigniewOchman** [kadaster/klic-win#113]
Hello,

I'd like to bring to your attention an issue with KLIC 23G0557631. Within this KLIC, there is an object identified by the GML ID: `nl.imkl-KL1184.v_9_3242612`. This object contains a list of links, which are as follow:

```
<net:link xlink:href="nl.imkl-KL1184.v_9_3301003"></net:link>
<net:link xlink:href="nl.imkl-KL1184.v_9_3301010"></net:link>
<net:link xlink:href="nl.imkl-KL1184.v_9_3301023"></net:link>
<net:link xlink:href="nl.imkl-KL1184.v_9_3301024"></net:link>
```
However, upon inspection, it appears that the GML does not contain any of the linked objects. Could you please confirm if this situation is correct?

**Comment by FuatAkdeniz** [comment]
You can send an email with your contact details to fuat.akdeniz@kadaster.nl

**Comment by FuatAkdeniz** [comment]
The reason why there are objects in the XML that are referenced and yet cannot be found is clipping.
Clipping of the cable and pipe based on the excavation contractor's polygon in the application.
It is an accepted phenomenon.
