### ISSUE TITLE
getekendeFeatureCoordinaten -> getekendeGeometrie

### ISSUE THREAD

**Issue by hannesgeodan** [kadaster/klic-win#115]
Hallo,

Toen we begin dit jaar begonnen met het ontwikkelen aan de API voor terugmeldingen bij KLIC kwamen we `getekendeFeatureCoordinaten` tegen in `secundair` van de response berichten.  Toen had het vrijwel geen specificatie over de coordinaten.
Nu we dit weer eens onder de loep nemen zien we dat het inmiddels een soort van GeoJson geometrie is geworden met de naam `getekendeGeometrie`. 
Ik kan nergens goede documentatie vinden van het berichten model. Het kan een speld zijn in de hooiberg, maar misschien is het ook nergens goed gedocumenteerd.

Ik hoop dat jullie kunnen uitleggen welke waarden geaccepteerd dienen te worden voor dit veld (waarmee, naar ik aanneem, de geometrie van een afwijkende leiding getekend wordt).

En een vastgestelde JSON schema definitie zou ons ook erg helpen.

MVG

Hannes 
Geodan / GoConnect

**Comment by JustinRoodenburg** [comment]
Beste Hannes,

Het makkelijkste kun je kijken bij de [release van 10 januari 2023](https://github.com/kadaster/klic-win/blob/master/KLIC%20-%20Geplande%20werkzaamheden.md#planning-voor-release---10-januari-2023) 
Daarin staat een link naar de [specificatie voor de melder (grondroerder)](https://github.com/kadaster/klic-win/blob/master/Terugmelden%20Afwijkende%20Situatie) en een link naar de [specificatie van het afhandelen (netbeheerder)](https://github.com/kadaster/klic-win/blob/master/BMKL/BMKL%202.1/BMKL%202.1%20(B2B-koppeling%20beheerdersinformatie).md#overzicht-bmkl-apis-voor-afhandelen-afwijkende-situatie)

De `getekendeGeometrie` is inderdaad in GEOJSON formaat (inclusief type). Het betreft de coördinaten in RD formaat in de buurt van de terugmelding. Kan gebruikt worden als de terugmelder in de app bijvoorbeeld de werkelijke ligging getekend heeft.

Als er verder geen vragen meer zijn, wilt u dit issue dan weer sluiten?
In het vervolg kunt u ook uw vragen naar klic@kadaster.nl mailen.

 

Groeten,
Justin
Kadaster

**Comment by hannesgeodan** [comment]
Beste Justin,

Bedankt. Zou je dat op de documentatie kunnen toevoegen? 
Welke typen (`LineString` in ieder geval dus) kunnen we nog meer verwachten?

Groeten,

Hannes

**Comment by JustinRoodenburg** [comment]
Beste Hannes,

De types die toegestaan zijn, zijn gedocumenteerd op https://geojson.org/.
Het meest voor de hand liggend zou het gebruik zijn van `Point`, `LineString` of `Polygon`. Bijvoorbeeld als een kabel/leiding is getekend, of een gebied waarbinnen de genoemde kabel/leiding niet gevonden is.  Dat zijn ook de typen die je vanuit de Kadaster KLIC-viewer kan verwachten.
Echter, de specificatie geeft de ruimte om alle toegestane types te gebruiken. Het Kadaster valideert niet op de inhoud van het GEOJSON object.

Groeten,
Justin
Kadaster
