### ISSUE TITLE
Betrokken partijen uit de graafketen registreren bij het doen van een Graafmelding

### ISSUE THREAD

**Issue by DesmondPost** [kadaster/klic-win#116]
Vanuit het KLO (Kabel en Leiding Overleg) komt de wens de graafketen beter te registreren voordat de werkzaamheden worden uitgevoerd. Dit vertaalt zich concreet in het registreren van Initiatiefnemer, hoofdaannemer en eventuele onder opdrachtgevers en -nemers tot en met de uitvoerende partij bij het doen van een graafmelding. 

Het KLO wil het KGO vragen deze wijziging mee te nemen met de wijzigingen die reeds geplanned staan. 

Met deze wijziging beoogd het KLO de bestuurbaarheid van de graafketen in algemene zin beter te kunnen inrichten, hetgeen een waardevolle bijdrage zal leveren aan het voorkomen van graafschades.

**Comment by kad-scholm** [comment]
Verplaatst naar de geonovum issuelijst https://github.com/Geonovum/imkl2015-review/issues/357
