### ISSUE TITLE
Specificeren van ondergrondse waterafvoer-infrastructuur: drains, infiltratiekratten, waterberging

### ISSUE THREAD

**Issue by rtimmers** [kadaster/klic-win#118]
Er worden steeds meer ondergrondse oplossingen voor tijdelijke (hemel)wateropslag gerealiseerd. Deze staan nu niet op de Klic en kunnen leiden tot graafschade aan deze infrastructuur. Dit voorstel maakt het mogelijk om deze ondergrondse infrastructuur op te nemen in de KLIC. 

Voorstel is het specificeren van deze waterbergings-infrastructuur (in IMKL). Onderdeel van specificatie is het visualiseren van deze infrastructuur, omdat het vaak vlakken/polygonen zijn.

**Comment by FuatAkdeniz** [comment]
@rtimmers We gaan dit met issue https://github.com/Geonovum/imkl2015-review/issues/291 oplossen.
Wil je dit sluiten!

Dank je
