### ISSUE TITLE
H 5 Waardenlijsten waardes mogen maar 50 tekens zijn

### ISSUE THREAD

**Issue by alex3305** [kadaster/klic-win#12]
In de waardenlijsten worden alle waardes (values) gelimiteerd op 50 tekens. Echter zijn er al voorbeelden in de API specificatie die over de specifieke 50 tekens heen gaan. Ons voorstel zou dan ook zijn om het maximaal aantal tekens niet te hanteren, of om een (veel) hogere waarde te kiezen. Voorbeelden:
- De beheerdersinformatie komt uit de centrale voorziening (57 tekens)
- Nog niet alle beheerdersinformatie is geleverd en goedgekeurd (62 tekens)

**Comment by martinborgman** [comment]
De values hadden ongelimiteerd gedefinieerd moeten zijn.
Wordt aangepast in de volgende versie van het document

**Comment by martinborgman** [comment]
Is gefixed in versie 0.76
