### ISSUE TITLE
ongeldige url en wat voor certificaat

### ISSUE THREAD

**Issue by MannusEtten** [kadaster/klic-win#120]
PKI overheidscertificaat nodig:
Zie https://www.logius.nl/domeinen/toegang/pkioverheid/aanvragen

deze url vond ik bij client credentials beschrijving, die werkt niet meer

Ik wil graag als ServiceProvider aansluiten op de REST API om namens de grondroerder een klic-aanvraag in te sturen.
Ik heb mijn Eherkenning-leverancier Reconi gevraagd wat voor type certificaat ik hiervoor nodig heb. Ze hebben totaal geen idee.

Kunnen jullie aangeven wat voor soort SSL-certificaat hiervoor benodigd is?

**Comment by FuatAkdeniz** [comment]
Beste Manus,

Kan je deze vraag sturen naar klic@kadaster.nl, mijn collega's pakken dit dan op.

**Comment by MannusEtten** [comment]
Dank, ik heb het issue volgens mij inmiddels opgelost
