### ISSUE TITLE
H 2.2 / 3.4 Communicatie, Content-Type header voor POST requests

### ISSUE THREAD

**Issue by alex3305** [kadaster/klic-win#13]
Wij zouden graag bij HTTP POST requests een 'Content-Type' HTTP header meesturen. Wanneer dat gebeurt kan de REST API namelijk een 415 Unsupported Media Type HTTP status code terugsturen, als er een 'verkeerde' payload meegestuurd wordt. Dit verduidelijkt dan de foutmelding voor de implementatie ontwikkelaar. Deze header zou dan tevens verplicht kunnen zijn voor "Sturen melding gebiedsinformatieaanvraag gezien", aangezien het daar mogelijk is om zowel een JSON als XML te versturen.

**Comment by martinborgman** [comment]
Het Content-Type is volgens mij zelfs verplicht.
De tekst in H 2.2 is inderdaad niet duidelijk.
Wordt aangepast in de volgende versie van het document.

**Comment by martinborgman** [comment]
Is gefixed in versie 0.76
