### ISSUE TITLE
H 3 / 4 / 5, Not Acceptable status header

### ISSUE THREAD

**Issue by alex3305** [kadaster/klic-win#14]
Voor de helderheid van de API specificatie zouden wij graag zien dat een HTTP status code 406, Not Acceptable teruggestuurd wordt wanneer er een request wordt gedaan met een niet ondersteunde Accept-header.

**Comment by martinborgman** [comment]
Wordt toegevoegd in de volgende versie van het document.

**Comment by martinborgman** [comment]
Is gefixed in versie 0.76
