### ISSUE TITLE
H 3.3.2 Zoeken naar gebiedsinformatieaanvragen, GML 3.2.1 non-deprecated elementen gebruiken

### ISSUE THREAD

**Issue by alex3305** [kadaster/klic-win#15]
In het voorbeeld XML wordt er 'coordinate' en 'coordinates' gebruikt voor het beschrijven van geografie, echter zijn deze elementen zijn sinds GML 3.1 _deprecated_. Dit staat beschreven in _OpenGIS® Geography Markup Language (GML) Implementation Specification version 3.1.1_:

> #### 9.1.3.5 gml:CoordinatesType, gml:coordinates
> 
> This type is deprecated with GML version 3.1.0 for tuples with ordinate values that are numbers.
> 
> CoordinatesType is a text string, intended to be used to record an array of tuples or coordinates.
> 
> While it is not possible to enforce the internal structure of the string through schema validation, some optional attributes have been provided in previous versions of GML to support a description of the internal structure. These attributes are deprecated with GML version 3.1.0. [...]
> 
> [...] The "coordinates" element is deprecated with GML version 3.1.0. [...]

Wij zouden graag zien dat de elementen gml:pos en gml:posList gebruikt worden, aangezien deze elementen door het OGC aanbevolen worden.

**Comment by martinborgman** [comment]
Voor zover we XML/GML daadwerkelijk gaan ondersteunen zal de geometrie conform GML 3.2.1 zijn, net als in IMKL2015. 
Wordt aangepast in de volgende versie van het document.

**Comment by martinborgman** [comment]
Is gefixed in versie 0.76
