### ISSUE TITLE
H 3.3.2 Ophalen gebiedsaanvraag, SRS met OGC urn

### ISSUE THREAD

**Issue by alex3305** [kadaster/klic-win#16]
In de voorbeeld geometrie staat het SRS beschreven met een naam, zoals `EPSG:28992`, echter heeft het OGC in 2007 de _OGC® Best Practices Paper_ uitgegeven, waar in het subdocument _Definition identifier URNs in OGC namespace_ staat beschreven dat het een best practice is om SRS'en in URN definities uit te drukken. Ook in de [GeoJSON](http://geojson.org/) specificatie van het IETF wordt er met deze URN's gewerkt. 

Wij zouden daarom graag zien dat de SRS volgens de URN specificatie van het OGC wordt opgebouwd. Tevens vereenvoudigd dit de automatische verwerking en ondubbelzinnigheid van de gegeven SRS.

**Comment by martinborgman** [comment]
Wordt aangepast in de volgende versie van het document.
Heb je overigens de specificatie graag met of zonder versie, urn:ogc:def:crs:EPSG:6.9:28992 of urn:ogc:def:crs:EPSG::28992.

**Comment by alex3305** [comment]
In het document [URNs of definitions in ogc namespace](https://portal.opengeospatial.org/files/?artifact_id=8814) (PDF) staat het volgende beschreven:

> # 7 URN formats for definitions in ogc namespace
> 
> ## 7.1 URN format for single objects
> 
> The “version” part of these URNs can be omitted when the referenced definition does not
> have a version, and the referenced definition is not specific to an authority version. When
> included, the “version” shall be recorded in the format specified by the authority,
> sometimes “N.N.N” or “N.N”, where each “N” stands for an integer. No "v" or other
> version prefix shall be included. 

Volgens mij houdt dat in dat beide varianten toegelaten zijn. Dat lijkt ons de beste aanpak.

**Comment by martinborgman** [comment]
Als ik heel goed zoek dan krijg is het idee dat het genoemde versie nummer "6.9" het versienummer van de EPSG database is en dus niet zo zeer het versienummer van de referentie definitie van EPSG 28992 is.
Heeft EPSG 28992 wel een versie? http://www.epsg-registry.org/report.htm?type=selection&entity=urn:ogc:def:crs:EPSG::28992&reportDetail=long&style=urn:uuid:report-style:default-with-urn&style_name=OGP%20Default%20With%20Urn&title=bla

**Comment by martinborgman** [comment]
We gebruiken vooralsnog geen versienummer.
Is gefixed in versie 0.76.
