### ISSUE TITLE
GeoJSON

### ISSUE THREAD

**Issue by FuatAkdeniz** [kadaster/klic-win#17]
Hi Fuat,

TechM (System Integrator from KPN) has a question regarding the interface between the Kadaster site and the KPN site concerning KLIC WIN. As I understood the 
proposal is to use JSON technology for the API and we will send gml files across using the API (interface). There will be only one GJSON component in this, the request which 
comes from the Kadaster will hold a GJSON component. 

Can you please confirm this and if it’s different as I explained above then please let us know how it should be. If the explanation as mentioned above is correct then can you 
please explain why we don’t use GJSON for the vector data instead of gml files?
Thanks!

Regards,

John

John van Luijk
Domain Architect OSS GIS
KPN NetCo FO N&S Development
+31 6 537 603 01

**Comment by martinborgman** [comment]
If I understand the question correctly, there are two GeoJSON properties in the gebiedsinformatieaanvraag object, the properties are named informatieGebied and graafGebied.
You can see examples of both on page 17 of the 0.80 version of the document

**Comment by martinborgman** [comment]
Closing this issue
