### ISSUE TITLE
Paragraaf 2.3.1.1 Typo huisaansluitschets adres met onjuiste omschrijvingen

### ISSUE THREAD

**Issue by stephanmahieu** [kadaster/klic-win#21]
Paragraaf 2.3.1.1 bevat een typo (Huisaansluistchets Adres) en in de omschrijvingen wordt ten onrechte gerefereerd aan het bezoekAdres van de gebiedsinformatieaanvrager i.p.v. huisaansluitschetsadres.

**Comment by martinborgman** [comment]
Dit is opgelost in versie 1.0 van het document.
