### ISSUE TITLE
Netinformatie: geen API gepubliceerd voor aanleveren informatie centrale voorziening

### ISSUE THREAD

**Issue by mkkranen** [kadaster/klic-win#28]
In paragraaf 2.1 wordt BMKL2.0 afgebakend. Onderdeel van BMKL2.0 is ook het Netinformatie bericht t.b.v. het aanleveren van informatie aan de centrale voorziening. Hiervoor is echter geen API gepubliceerd. Wanneer komt hiervoor wel een API ter beschikking?

**Comment by KeesvdGraaf** [comment]
Ik ondersteun deze vraag namens PWN: wanneer wordt deze API gepubliceerd?

**Comment by martinborgman** [comment]
Een API voor het aanleveren van NetInformatie t.b.v. de centrale voorziening heeft nog geen hoge prioriteit.
We gaan vooralsnog beginnen met een web interface waarbij de aangeleverde informatie gevisualiseerd wordt voor controle.

**Comment by ghost** [comment]
Is er al zicht wanneer deze API, voor de aanlevering van netinformatie, wordt gepubliceerd?

**Comment by FuatAkdeniz** [comment]
Eind augustus 2016 zal een eerste versie van het document worden gepubliceerd.

**Comment by bvlangen** [comment]
Inmiddels is er een B2B API beschikbaar voor het actualiseren van netinformatie en documenten. 

Zie voor een handleiding van actualiseren van netinformatie: https://github.com/Kadaster/KLIC-WIN/blob/master/Actualiseren/Netinformatie/B2B-koppeling%20actualiseren%20netinformatie.md

Een handleiding voor het actualiseren van documenten is hier te vinden: https://github.com/Kadaster/KLIC-WIN/blob/master/Actualiseren/Documenten/B2B-koppeling%20actualiseren%20documenten.md
