### ISSUE TITLE
Opmerkingen / vragen namens PWN

### ISSUE THREAD

**Issue by KeesvdGraaf** [kadaster/klic-win#29]
Bij lezing van v0.90 heb ik de volgende opmerkingen: 
1. Typo: begin pag 7; verwijzing 2.5 moet 2.6 zijn.
2. Pag 9: Vraag:  'gebiedsInformatieAanvragen/{id}/ (GET)' zie ik niet direct terug in figuur daarvoor.  Idem mbt 'beheerdersInformatie/gebiedsInformatieAanvraagId/{id} (GET)'. 
3. Pag 11: aanvraagID is blijkens voorbeelden iets anders dan KLIC-nummer. Ik mis het KLIC-nummer. Alliander heeft dat ook geconstateerd. In reactie is dit een business-vraag genoemd. 
   Mi moet KLIC-nummer er altijd bij staan, dit is het meest éénduidige nummer voor communicatie op gebruikersniveau. Nu is dat nummer er ook en dit zou niet mogen verdwijnen.
4. Pag 17 / par 3.2: Hoe vraag je de aanvragen op die je nog niet hebt ontvangen? Kan dit obv status? 
   NB: Eerdere reactie op dit punt is mij nog niet voldoende duidelijk.
5. Pag 26: Voorbeeld met BAG-adres bovenaan bevat geen postcode. Toch verplicht?
6. Pag 30/ par 4.3.: "GET klic/v1/ws/beheerdersInformatie/gebiedsInformatieAanvragen/{id}"
   Waar staat deze in een figuur? Graag verwijzing tbv duidelijkheid.

NB: Misschien zijn punten al eerder opgemerkt, dan zijn ze bij controle van de issues door mij over het hoofd gezien en zijn ze ten overvloede.

**Comment by martinborgman** [comment]
Bedankt voor het commentaar.
1. De verwijzingen worden dynamische verwijzingen.
2. De plaatjes worden vervangen.
3. Het KLIC-nummer is in essentie een order nummer en sinds KLIC v5 hebben we binnen KLIC ook een echt order nummer. Dit order nummer wordt nu ook al met alle gebruikers gecommuniceerd en maakt dus ook deel uit van de gebiedsinformatie-aanvraag.
4. Heel kort gezegd door een GET op  /gebiedsInformatieAanvragen/netbeheerder/?gebiedsInformatieAanvraagStatus=open. De exacte URL staat nog niet helemaal vast.
5. Goed gezien, pas ik aan.
6. Is hetzelfde als punt 2, de plaatjes worden vervangen.

**Comment by martinborgman** [comment]
De opmerkingen zijn verwerkt in versie 1.0 van het document
