### ISSUE TITLE
H 3.2.1 Zoeken naar gebiedsaanvragen request, parameter status onduidelijk

### ISSUE THREAD

**Issue by alex3305** [kadaster/klic-win#3]
Bij het zoeken naar gebiedsaanvragen kunnen er meerdere parameters meegegeven worden in het request. In hoofdstuk 2 van de voorgestelde API specificatie staat bij alle requests beschreven in hoeverre request parameters optioneel, conditioneel of verplicht zijn. In deze paragraaf mist deze status per parameter, of wanneer ze allemaal dezelfde status hebben, een begeleidende tekst.

**Comment by martinborgman** [comment]
Dit corrigeren we in de volgende versie van het document.

**Comment by martinborgman** [comment]
Is gefixed in versie 0.76
