### ISSUE TITLE
Datatransport: aantal kabels d.m.v. annotatie

### ISSUE THREAD

**Issue by mkkranen** [kadaster/klic-win#30]
Via het KLIC-WIN contactformulier heb ik de volgende vraag gesteld:

> Netbeheerders van telecom (datatransport) moeten in de huidige versie van het IMKL het aantal kabels in een HDPE buis aangeven. Een manier die toegestaan is, is om dat via annotatie duidelijk te maken. Blijft deze mogelijkheid binnen IMKL2015 toegestaan?
> De achtergrond is dat bij veel klein(er)e telecom-netbeheerders gegevens alleen in de vorm van CAD-tekeningen beschikbaar zijn, waarbij het aantal kabels alleen uit de annotatie blijkt. Conformeren aan IMKL2015 is dus potentieel een grote inspanning/kostenpost.

Het antwoord van het Kadaster luidde: 

> Dit is meer een sectorvraag. In het model is hier namelijk een speciaal attribuut voor opgenomen ‘buismateriaalType’. U kunt een issue aanmaken op GitHub https://github.com/Kadaster/KLIC-WIN  Dit kan dan door één van de Werkgroepen beantwoord worden.
> Ons advies zal ook zijn dat als er een attribuut is voor de informatie die u wilt communiceren, dat u ook dat attribuut daarvoor moet gebruiken en dat u de informatie niet in een andere vorm communiceert. 

Bij deze leg ik dus de vraag hier als issue voor.

**Comment by martinborgman** [comment]
Aangezien dit een IMKL inhoudelijke vraag is wil ik voorstellen dit issue aan te maken op GitHub https://github.com/Geonovum/imkl2015-review.

**Comment by martinborgman** [comment]
Deze vraag valt buten de scope van de API
