### ISSUE TITLE
Upper/Lowercase foutjes json voorbeelden waardenlijst

### ISSUE THREAD

**Issue by stephanmahieu** [kadaster/klic-win#31]
Op pagina 37 staat een json voorbeeld met een foutje tav upper/lowercase, BiNotificatieStatussen moet met een kleine letter beginnen.
`{ 
  "key": "https://api.kadaster.nl/klic/v1/cl/BiNotificatieStatussen/open", 
  "value": "Dit is een openstaande gebiedsinformatie-aanvraag" 
}`

Op pagina 41 staat een json voorbeeld met een foutje tav upper/lowercase, GiAanvraagStatussen moet met een kleine letter beginnen.
`{ 
  "key": "https://api.kadaster.nl/klic/v1/cl/GiAanvraagStatussen/open", 
  "value": "Er is een nieuwe gebiedsinformatie-aanvraag ingediend" 
}`

**Comment by martinborgman** [comment]
Is inderdaad niet correct, wordt aangepast in de volgende versie van het document.

**Comment by martinborgman** [comment]
Volgende versie is gepubliceerd.
