### ISSUE TITLE
Verduidelijk request en response parameters betreffende id/key t.a.v. codelijsten

### ISSUE THREAD

**Issue by stephanmahieu** [kadaster/klic-win#32]
In de documentatie wordt niet goed duidelijk uitgelegd dat bij het zoeken met een parameter uit de codelijst een id moet worden gebruikt en dat het id het gedeelte is na de laatste slash van een key (URI). In de response wordt wel de volledige key (URI) wordt geretourneerd. Aan de hand van de voorbeelden is het wel af te leiden maar wellicht is het verstandig de documentatie t.a.v. dit punt iets meer te verduidelijken.

Voorbeeld:
Zoeken naar gebiedsinformatie-aanvragen met request parameter aanvraagSoort bijvoorbeeld  `aanvraagSoort=orientatiemelding`.
In de json response wordt de volledig key geretourneerd: `"aanvraagSoort": "https://api.kadaster.nl/klic/v1/cl/aanvraagSoorten/orientatiemelding"`

**Comment by martinborgman** [comment]
Wordt verduidelijkt in de volgende versie van het document

**Comment by martinborgman** [comment]
Volgende versie is gepubliceerd
