### ISSUE TITLE
Attribuutbeschrijving  netinformatie

### ISSUE THREAD

**Issue by ghost** [kadaster/klic-win#34]
In hoofdstuk 4 is niet opgenomen een attribuutbeschrijving van de opgeleverde netinformatie van de geïdentificeerde netbeheerder. Graag deze opnemen voor compleetheid (gelijk aan de attribuutbeschrijving van de gebiedsinformatie [paragraaf 3.4.2]).

**Comment by martinborgman** [comment]
De netinformatie is conform imkl2015-wion.xsd en dit is uitvoerig beschreven in de IMKL2015.
Zie https://github.com/Geonovum/imkl2015 voor de laatst gereleaste versie van de IMKL2015.
Voor issues ga naar https://github.com/Geonovum/imkl2015-review

**Comment by martinborgman** [comment]
Ik ga ervan uit dat deze vraag naar tevredenheid beantwoord is
