### ISSUE TITLE
Eisen/wensen geautomatiseerd aanleveren netinformatie

### ISSUE THREAD

**Issue by DoekeleR** [kadaster/klic-win#36]
In het documetn 'IA Geautomatiseerd actualiseren 2016-07-07.ppt' zijn wensen aangegeven vanuit netbeheerders t.a.v. het geautomatiseerd aanleveren van netinformatie (sheet 4). Hierin is de wens

 '_dat een serviceprovider aanleveringen namens een netbeheerder volledig kan afhandelen (enkel en alleen als deze daarvoor gemandateerd is de door de betreffende netbeheerder_).'

Als prioriteit **2** aangemerkt. 

Hoe is tot deze prioriteit gekomen? Wie hebben de prioriteiten bepaald?

Voor Service Providers, en daarmee ook voor alle netbeheerders die via een service provider gaan aansluiten, is deze wens **prioriteit 1**. Dit is in het belang van alle netbeheerders die via een service provider aansluiten. Deze wens is nodig om de kosten laag te kunnen houden (geen handmatige acties), en dus in het belang van 'de kleinere netbeheerders', die niet de kennis en kunde in huis hebben om de aansluiting zelf te realiseren. Is het mogelijk dat deze wens prioriteit 1 krijgt?

**Comment by FuatAkdeniz** [comment]
Prioriteit moet je in deze meer lezen als in welke volgorde de functionaliteit gebouwd worden?
Allereerst dat de netbeheerder zelf gebruik kan maken van deze functionaliteit en vervolgens dat de Serviceprovider voor de netbeheerder werkzaamheden kan uitvoeren.
