### ISSUE TITLE
NTD Testfacility not available

### ISSUE THREAD

**Issue by stephandeckers** [kadaster/klic-win#37]
The NTD-testfacility contained a button 'Selecteer Bestand' to upload a new zipfile. This button is gone and we cannot test our zipfiles. Attached the situation as I see it now and the situation from the manual

**Current:**
![button gone](https://cloud.githubusercontent.com/assets/1563863/18581017/f88f281a-7bfe-11e6-9551-cc7dca010447.png)

**Manual :**
![button present](https://cloud.githubusercontent.com/assets/1563863/18581018/f88f6d66-7bfe-11e6-95b4-8bc67a15ce3c.png)

**Comment by FuatAkdeniz** [comment]
"Selecteer bestand" is not available if the dataowner has a status "Gereed voor handmatige controle".
Please check the status at the first page and see if thee is a status is "Gereed voor handmatige controle" and press on the button "Controleren". Here you can choose the action "Godkeuren" or "Afkeuren".
See chapter "3.2.3 Tabblad Logbestand" of the instructions.

The dataowner has to choos one of the options before uploading another file.
You can mail klic-win@kadaster.nl for further questions.

**Comment by stephandeckers** [comment]
Ok, thanks.
