### ISSUE TITLE
Typo in BMKL documentatie

### ISSUE THREAD

**Issue by martinborgman** [kadaster/klic-win#39]
Sebastiaan Baars schrijft:

In de KLIC-WIN Netbeheerder API v1.1 documentatie zit een typo. Bij header 5.15 staat klic/v1/ci/validatieStapMeldingLeves en dit moet volgens mij klic/v1/ci/validatieStapMeldingLevels zijn :smile:

**Comment by bvlangen** [comment]
Documentatie is als verouderd bestempeld en in de map 'oud' gezet. 
KLIC-WIN Netbeheerder API is nu de 'Beheerdersinformatie' API geworden aka BMKL 2.0. 
Documentatie is hier te vinden: https://github.com/Kadaster/KLIC-WIN/blob/master/Berichtenprotocol%20KLIC-WIN/B2B-koppeling%20decentraal%20aanleveren%20BMKL%202.0.md
