### ISSUE TITLE
H 3.2.1 Zoeken naar gebiedsaanvragen request met waardenlijst(en)

### ISSUE THREAD

**Issue by alex3305** [kadaster/klic-win#4]
Bij het zoeken naar gebiedsaanvragen kunnen in de parameters waarden vanuit codelijsten meegegeven worden. In de API specificatie staat niet duidelijk beschreven of hier de key of de value vanuit de codelijst meegegeven moet worden.

**Comment by martinborgman** [comment]
Het moet altijd de key zijn, de value is meer bedoeld voor in een webapplicatie.
Dit wordt aangepast in de volgende versie van het document.

**Comment by martinborgman** [comment]
Is gefixed in versie 0.76
