### ISSUE TITLE
API voor INSPIRE

### ISSUE THREAD

**Issue by DoekeleR** [kadaster/klic-win#41]
We hebben in de sessie van 23 september begrepen dat er **geen** API beschikbaar komt om afgehandelde INSPIRE aanvragen te downloaden. dit was wel onze verwachting. Is er een mogelijkheid om deze wens, die veel netbeheerders hebben, opnieuw onder de aandacht te brengen?

**Comment by KeesvdGraaf** [comment]
Hierbij ondersteun ik het voorstel van Doekele. 
Drinkwaterbedrijven waarvoor ik werk hebben behoefte aan deze API.

**Comment by HenkGeurts** [comment]
Ik heb een hiervoor op 10 oktober een wijzigingsverzoek ingediend, de vertegenwoordigers van de netwerkbedrijven en de drinkwaterbedrijven zijn geinformeerd. Op 28 oktober wordt het verzoek behandeld in de WG blauwdruk. 
vrgr, Henk Geurts

**Comment by FuatAkdeniz** [comment]
Zal niet opgepakt worden.
