### ISSUE TITLE
Need for BMKL message examples

### ISSUE THREAD

**Issue by mvvaalen** [kadaster/klic-win#42]
For BMKL messages, we need to have the examples for:

•         /gebiedsInformatieAanvragen/netbeheerder: This will return the list of map requests. We require an example of the exact format what this URI will return.
•         /gebiedsInformatieAanvragen/{id}/netbeheerder: This will return the map request with specific ID. We require an example of the exact format what this URI will return when we specify the KLIC ID.
•         /gebiedsInformatieAanvragen/{id}/netbeheerder/gezien: This will be used for posting the acknowledgement / confirmation of specific KLIC Id. We require the format of what to be posted as acknowledgement.
- we need to know how the ZIP file containing the XML, PDFs etc needs to be sent. Will it be in JSON or SOAP format. We need to know the way of communication and an example of the exact format to be used.

Martin van Vaalen

**Comment by FuatAkdeniz** [comment]
We don't have these examples yet. Because of the priority of other functionality. We will get back soon.

**Comment by FuatAkdeniz** [comment]
With the Swagger tooling you can find examples for the messages
https://github.com/Kadaster/KLIC-WIN/blob/master/Berichtenprotocol%20KLIC-WIN/B2B-koppeling%20decentraal%20aanleveren%20BMKL%202.0.md

The BMKL functionality is available since 13 april 2017

An example ZIP file is not available yet.

**Comment by mvvaalen** [comment]
Dank je Fuat,

Ik zal onze leverancier meteen informeren.

Mvr gr
Martin van Vaalen

Van: FuatAkdeniz [mailto:notifications@github.com]
Verzonden: vrijdag 21 april 2017 11:16
Aan: Kadaster/KLIC-WIN
CC: Vaalen, Martin van; Author
Onderwerp: Re: [Kadaster/KLIC-WIN] Need for BMKL message examples (#42)


With the Swagger tooling you can find examples for the messages
https://github.com/Kadaster/KLIC-WIN/blob/master/Berichtenprotocol%20KLIC-WIN/B2B-koppeling%20decentraal%20aanleveren%20BMKL%202.0.md

The BMKL functionality is available since 13 april 2017

An example ZIP file is not available yet.
