### ISSUE TITLE
Lengte bronhoudercode is xsd niet correct

### ISSUE THREAD

**Issue by djbulsink** [kadaster/klic-win#43]
In KlicVoorzorgsmaatregelenBeheer-0.1.xsd staat dat de lengte van bronhoudercode maximaal 5 karakters mag zijn. Dit is niet correct het moet maximaal 6 karakters zijn. In de KlicDocumentenBeheer.xsd staat dit wel goed.

**Comment by FuatAkdeniz** [comment]
De opmerking terecht. In nieuwere versies is deze al aangepast, maar nog niet gepubliceerd.
