### ISSUE TITLE
Moeten in 2.3.1 onder zowel "aanvrager" als "opdrachtgever" bezoekAdres en postbusAdres niet beiden conditioneel zijn?

### ISSUE THREAD

**Issue by mvvaalen** [kadaster/klic-win#44]
Regarding the BMKL request validations (2.3.1 Parameters map request), for the 'aanvrager', both 'bezoekAdres' and 'postbusAdres' are conditional and the attributes inside those are also conditional. But for 'opdrachtgever', 'bezoekAdres' is required and 'postbusAdres' is conditional, but the attributes inside both 'bezoekAdres' and 'postbusAdres' are either conditional or optional and condition depends on each other attributes. We feel that 'bezoekAdres' should be conditional.
Same applicable for the 'bezoekAdres' and 'postbusAdres' under 'opdrachtgever'.

**Comment by martinborgman** [comment]
We discussed this issue and we agree.
In the next version of the API document bezoekAdres and postbusAdres will be documented as conditional for both aanvrager and opdrachtgever.
The API does not enforce the condition however. The condition is enforced at data entry.
