### ISSUE TITLE
Wat is voorwaarde bij aanvraagDatum, giAanvraagstatus en soortWerkzaamheden?

### ISSUE THREAD

**Issue by mvvaalen** [kadaster/klic-win#45]
In 2.3.1, 'aanvraagDatum', 'giAanvraagStatus' and 'soortWerkzaamheden' are mentioned as Conditional. But the condition is not mentioned in the Description column like in case of other conditional attributes.

**Comment by martinborgman** [comment]
Both aanvraagDatum and giAanvraagStatus should be required.
soorWerkzaamheden is required for “aanvraagSoort” = “graafmelding” | "orientatieverzoek". The minimum number of entries in the soorWerkzaamheden is now 1 and the maximum number of entries is 6.
soorWerkzaamheden does not exist for "aanvraagSoort" = "calamiteitenmelding".
We will update this in the next version of the API description.
