### ISSUE TITLE
Optional tags give error when not added and also when no values or null value given 

### ISSUE THREAD

**Issue by sachinSargar** [kadaster/klic-win#46]
Tags like ValidFrom, ValidTo, verticalPosition, DuctWidth, WarningType are optional as per IMKL. When we dont give this tags the testing portal gives error. And also when we give no values or NULL value it gives error.
Find the attachement for the errors sreen shots
[Validation Issue.docx](https://github.com/Kadaster/KLIC-WIN/files/665532/Validation.Issue.docx)

**Comment by martinborgman** [comment]
ValidFrom, verticalPosition, DuctWidth and WarningType are controlled by XSD and they have a cardinality of 1, so they are required. You are however allowed to provide no value but then you must provide a valid nilReason. Please read [INSPIRE Data Specification on Utility and Government Services – Technical Guidelines](http://inspire.ec.europa.eu/id/document/tg/us)  about voidable.

ValidTo is optional. In your example, reading the XML the parser was expecting to find ValidTo or verticalPosition but found something else. For verticalPosition see stament above.

As for your last issue "heeftExtraInformatie" the error only states that you are referencing a gml feature with a gml id not found in the file.

As for code lists in general, you can only use value agreed upon and documented by Geonovum.

**Comment by bvlangen** [comment]
Issue has been answered and no further feedback was received, I presume the reported issue is resolved.
Therefore closing issue
