### ISSUE TITLE
Code list issue for heeftExtraInformatie tag in Appurtenance feature

### ISSUE THREAD

**Issue by sachinSargar** [kadaster/klic-win#47]
In Appurtenance feature for tag heeftExtraInformatie was decided to send ‘Type’ of feature if it is different from IMKL type. But there is no code list value for the tag. testing facility is gving error. 

Please find the doc for discription and the screen shot of the error.

[Validation Issue - heeftExtraInformatie.docx](https://github.com/Kadaster/KLIC-WIN/files/666104/Validation.Issue.-.heeftExtraInformatie.docx)

**Comment by martinborgman** [comment]
The error simply show that you reference an object that doesn't exist. For example you are referencing a gml feature with gml id "Spoel". This is probably not what you intended.

As for code lists, you cannot use codelist value that are not documented in the code lists [here](https://register.geostandaarden.nl/waardelijst/imkl2015/1.1/).
If you think the lists are incomplete please report this as an issue [here](https://github.com/Geonovum/imkl2015-review).

**Comment by sachinSargar** [comment]
Yes we understood that it is expecting code list but the for the heeftExtraInformatie property there is no code list mentioned in the XLSX provided. I am unable to understand if the code list is not present for the tag why it is validating for the code list.
Please suggest us what to do validate that tag.

**Comment by martinborgman** [comment]
The value stored in heeftExtraInformatie is not a codelist value but a gml:id of a feature of type ExtraInformatie.
In your example you have an Appurtenance. With heeftExtraInformatie you can attach "extra" information to this Appurtenance such as ExtraDetailinfo, Annotatie, Maatvoering and/or AanduidingEisVoorzorgsmaatregel.
As with the extraGeometrie you can attach an ExtraGeometrie feature to your Appurtenance. In the real world your Appurtenance probably isn't a point object. To give your Appurtenance some meaningful geometry you should attach a ExtraGeometrie feature with this geometry to your Appurtenance.

**Comment by bvlangen** [comment]
Issue has been answered and no further feedback was received, I presume the reported issue is resolved.
Therefore closing issue
