### ISSUE TITLE
Missing rotatiehoekSymbool in DiepteTovMaaiveld feature

### ISSUE THREAD

**Issue by sachinSargar** [kadaster/klic-win#48]
As per the xls IMKL2015 v 1 1_object-attributen-ExtraRegels.xlsx, 'rotatiehoekSymbool' property is mentioned, but in xsd 'IMKL2015-wion.xsd' its missing. 
Please suggest what to do for the issue.
Please find the screen shot of the xlsx attached
![rotatieissue](https://cloud.githubusercontent.com/assets/22631958/21500113/9c8d068c-cc61-11e6-833e-01ec33eef0a8.jpg)

**Comment by martinborgman** [comment]
If you look in the xsd here https://register.geostandaarden.nl/gmlapplicatieschema/imkl2015/1.1/IMKL2015-wion.xsd you will find that 'rotatiehoekSymbool' is mentioned 7 times.
'DiepteTovMaaiveldType' uses the definition of 'DiepteType' were it is mentioned.

**Comment by bvlangen** [comment]
Issue has been answered and no further feedback was received, I presume the reported issue is resolved.
Therefore closing issue
