### ISSUE TITLE
H 3.2.1 Zoeken naar gebiedsaanvragen met datum en tijd

### ISSUE THREAD

**Issue by alex3305** [kadaster/klic-win#5]
Bij het zoeken naar gebiedsaanvragen is het mogelijk om een datum en tijd mee te geven. Dit is in het formaat ISO 8601 volgens de huidige specificatie. Echter is het niet geheel duidelijk in welk formaat van de ISO 8601 formaat gezocht kan en mag worden en worden er in de voorbeelden geen tijdzones gedefinieerd. 

Ons voorstel zou dan ook zijn om de mogelijkheid te bieden om te zoeken op datum vanaf 00:00 volgens formaat: **2015-10-21**, waarbij er een zero-offset tijdszone wordt gehanteerd, dus eigenlijk **2015-10-21T00:00:00Z**. Tevens zou er dan de mogelijkheid geboden kunnen worden om op specifieke datum en tijd te zoeken volgens de volgende formaten: **2015-10-21T15:41:36+01:00** en **2015-10-21T15:41:36Z**. Dan is er namelijk geen onduidelijkheid meer over de eventuele tijdszone.

**Comment by martinborgman** [comment]
Dat was wat mij betreft ook zo de bedoeling.
Dit passen we aan in de volgende versie van het document.

**Comment by martinborgman** [comment]
Er mankeerde nog meer met het zoeken op datum. Dit is opgelost in versie 0.80
