### ISSUE TITLE
My Kedaster Portal login issue.

### ISSUE THREAD

**Issue by sachinSargar** [kadaster/klic-win#52]
Loggin in to the 'My Kedaster' Portal is denied. Loggin ID used is 'UdayTechM'. Please reset the password.

**Comment by FuatAkdeniz** [comment]
Please use link: https://github.com/password_reset

**Comment by sachinSargar** [comment]
I want to reset password of  https://mijn.kadaster.nl/security/login with user ID 'UdayTechM'.
