### ISSUE TITLE
Hoe de gebiedsInformatieAanvragen-service te gebruiken om aanvragen aan graafschade te koppelen?

### ISSUE THREAD

**Issue by everhardt** [kadaster/klic-win#53]
Ik zou de gebiedsInformatieAanvragen-service willen gebruiken om bij het constateren van graafschade te achterhalen of er relevante aanvragen zijn gedaan.

Daarover twee vragen:
* Hoever gaat de gebiedsInformatieAanvragen service terug? Zijn alle ooit ingediende gebiedsInformatieAanvragen via dit endpoint op te vragen, of worden gesloten aanvragen op een gegeven moment gewist?
* Is het mogelijk `bbox` (bounding box) toe te voegen als parameter aan GET `/gebiedsInformatieAanvragen/netbeheerder/`, zodat enkel de aanvragen worden teruggegeven waarvan het graafgebied enige overlap met de `bbox` heeft?

**Comment by FuatAkdeniz** [comment]
De gebiedsInformatieAanvraag is maximaal 20 werkdagen beschikbaar. Het is van groot belang dat deze data zo snel mogelijk wordt opgehaald voor interne processen (netbeheerder).

De bounding box is niet als (spatial) selectiecriterium onderkend.
