### ISSUE TITLE
Documentatie? Netinformatie.xml bestanden dienen te beginnen met Netinformatie

### ISSUE THREAD

**Issue by JorritHanssonSE** [kadaster/klic-win#55]
Ik kon niet in de documentatie / op GitHub vinden dat de xml bestanden met netinformatie erin dienen te beginnen met het word netinformatie. Daar kreeg ik wel een foutmelding op via de NTD. Gaarne deze spelregels toevoegen aan de releasenotes aangezien dit een wijziging is (dit was bij NTD voor 1.2 nog niet zo).

**Comment by FuatAkdeniz** [comment]
Klopt dat dit is aangepast n.a.v. werkzaamheden voor "Actualiseren Voorzorgsmaatregelen".
Dit wordt z.s.m. aangepast in de genoemde documentatie.

Bedankt!

**Comment by FuatAkdeniz** [comment]
"Toelichting controles netinformatie KLIC" is aangepast hierop: 
https://github.com/kadaster/klic-win/blob/master/Toepassing%20IMKL/Toelichting%20controles%20netinformatie%20KLIC.md
