### ISSUE TITLE
Broncode validatieprocedures actualiseren

### ISSUE THREAD

**Issue by boonen** [kadaster/klic-win#56]
Het bestand [Toepassing IMKL/KLIC-WIN validatiecode.zip](https://github.com/kadaster/klic-win/blob/master/Toepassing%20IMKL/KLIC-WIN%20validatiecode.zip) is tamelijk oud. Kunnen jullie aangeven of er een actuelere versie beschikbaar is? Zo ja, is het mogelijk om die via een gestandaardiseerde methode aan te bieden (bij voorkeur via een Maven repository)?

Groeten,

Jan Boonen

**Comment by FuatAkdeniz** [comment]
Beste Jan,

Er zal geen actuele versie beschikbaar komen. Deze was éénmalig op verzoek van de sector beschikbaar gesteld.

Disclaimer: "Het Kadaster stelt gedurende het project KLIC-WIN deze validatiecode beschikbaar aan de netbeheerder of degene die in opdracht van hem werkzaamheden verricht, om naast de functionele beschrijving aanvullend inzicht te geven in de door het Kadaster gerealiseerde validaties van netinformatie. 
De validatiecode wordt door het Kadaster aangeboden om als hulpmiddel te worden gebruikt voor de realisatie van validaties van netinformatie bij netbeheerders. 
De validatiecode wordt ‘as – is’ aangeboden zonder enige vorm van garantie op volledigheid en juistheid. 
In geen geval is het Kadaster aansprakelijk voor schade of andere onregelmatigheden die veroorzaakt zijn of worden door gebruik of toepassing van de validatiecodes door een netbeheerder of degene die in opdracht van hem werkzaamheden verricht. 
Netbeheerders blijven te allen tijde verantwoordelijk voor de juiste, volledige en actuele aanlevering van hun netinformatie aan het Kadaster."
