### ISSUE TITLE
Ontbreken van volgnummer, wat is controle mechanisme voor volledigheid reeks Klic-meldingen

### ISSUE THREAD

**Issue by DoekeleR** [kadaster/klic-win#57]
Het viel ons op dat er geen 'volgnummer' meer is in IMKL1.2, zoals in huidige WION. Met dat volgnummer kunnen wij als Service Provider (SP) controleren of we de reeksen voor G, C en O meldingen compleet hebben. Daarmee kunnen we ook borgen dat we invulling geven aan de wettelijke plicht dat je alle klic-meldingen 5 jaar moet bewaren. Wij ontzorgen als SP daarin.

Verzoek om dit volgnummer weer op te nemen in IMKL.

**Comment by herman-vandenberg** [comment]
TCS: Volgnummer NIET meer opnieuw introduceren.

De BMKL-API geeft de netbeheerder veel mogelijkheden om alle beheerdersinformatie-aanvragen die voor de netbeheerder bedoeld zijn, op te vragen. Desgewenst op basis van selectiecriteria (bijv. status, datum, o.i.d.).
Een mogelijke kwetsbaarheid dat een belanghebbende netbeheerder mogelijk niet meegenomen zou worden, zit evengoed in toekennen van een volgnummer voor die netbeheerder.

In het oude BMKL-protocol was het missen van een bericht veel gevoeliger, omdat KLIC verantwoordelijk was om een "graafbericht" bij de netbeheerder te bezorgen, ook als deze niet bereikbaar was.
De huidige functionaliteit werkt naar tevredenheid.
