### ISSUE TITLE
API voor doen testmeldingen beschikbaar maken

### ISSUE THREAD

**Issue by DoekeleR** [kadaster/klic-win#58]
Het is op dit moment alleen mogelijk om handmatig testmeldingen te doen via mijn.kadaster.nl. Dit is een handmatig proces, wat veel tijd kost. 

We zouden graag via de B-2-B koppeling, zoals die er ook is bij de WION, via een API Testmeldingen willen doen. Daarmee kunnen we efficient testen.

**Comment by JorritHanssonSE** [comment]
Wij ondersteunen dit voorstel van Doekele (reeds gemeld bij Klic-Win@kadaster.nl , maar kan geen kwaad dit nogmaals te benoemen). Het kunnen doen van B2B testmeldingen zou het testproces voor onze klanten en onszelf flink kunnen versnellen en verbeteren.

**Comment by FuatAkdeniz** [comment]
Is ingericht met vernieuwing van de B2B aanvraag
