### ISSUE TITLE
H 3.2.2 Zoeken naar gebiedsaanvragen JSON response is geen lijst met URI's

### ISSUE THREAD

**Issue by alex3305** [kadaster/klic-win#6]
In de API specificatie staat onder hoofdstuk 3.2.2 dat er een lijst met URI’s wordt teruggegeven vanuit de API. Echter wordt er in het voorbeeld een lijst met (geneste) objecten teruggegeven. Wel hebben deze objecten echter altijd dezelfde key’s. Daarom zouden wij voorstellen om het daadwerkelijk een lijst met URI’s te maken, in de volgende vorm:

``` json
[
"https://api.kadaster.nl/klic/v1/ws/gebiedsInformatieAanvraag/995b3a08-de6a-44f1-8547-98273f1139bb/Netbeheerder",
"https://api.kadaster.nl/klic/v1/ws/gebiedsInformatieAanvraag/995b3a08-de6a-44f1-8547-98273f1139bb/Netbeheerder"
]
```

of eventueel in deze vorm, waarbij er tevens nog wat semantiek wordt bewaard:

``` json
[
{"gebiedsInformatieAanvraag": "https://api.kadaster.nl/klic/v1/ws/gebiedsInformatieAanvraag/995b3a08-de6a-44f1-8547-98273f1139bb/Netbeheerder"}, 
{"gebiedsInformatieAanvraag": "https://api.kadaster.nl/klic/v1/ws/gebiedsInformatieAanvraag/995b3a08-de6a-44f1-8547-98273f1139bb/Netbeheerder"}
]
```

Beide varianten zijn tevens gemakkelijker implementeerbaar in een API-client.

**Comment by martinborgman** [comment]
Ik zie in veel API's dat bij dit request type gewoon een lijst met objecten wordt teruggegeven in plaats van een lijst met links naar objecten.
Hoe denk jij daar over?

**Comment by alex3305** [comment]
Persoonlijk vind ik dat het extra _boxen_ van de URL in het response geen extra functionaliteit of semantiek toevoegt. Daarbij zou mijn voorkeur dus uitgaan naar de tweede variant die ik hierboven voorstel. Daarbij wordt er namelijk nog steeds verwezen naar **gebiedsInformatieAanvraag** en is naar mijn mening de expressiviteit van het response gewaarborgd.

**Comment by martinborgman** [comment]
Ik bedoelde eigenlijk meer:

``` json
[
   {
      "gebiedsInformatieAanvraag": {
         "aanvraagId": "5c25ee09-a2f4-4b94-a2a4-03b2617aaf9f",
         "aanvrager": {
            "bedrijfsNaam": "sample string",
            "email": "mail@mail.nl",
            "naam": "sample string",
            "telefoon": "088-1234567"
         },
         "referentie": "sample string",
.
.
.

         "aanvraagDatum": "2015-06-16T08:47:58.85+01:00",
         "orderNummer": "sample string",
         "gebiedsInformatieAanvraagStatus":  "https://api.kadaster.nl/klic/v1/cl/gebiedsInformatieAanvraagStatus/open"
      }
   },
   {
      "gebiedsInformatieAanvraag": {
         "aanvraagId": "cea8546d-fea9-48f7-9915-e382b0f22670",
.
.
.
      }
   }
]
```

**Comment by martinborgman** [comment]
Is gefixed in versie 0.76
