### ISSUE TITLE
Meenemen beschikbaarheid EV-brief bij validatie Buisleiding gevaarlijke inhoud

### ISSUE THREAD

**Issue by DoekeleR** [kadaster/klic-win#60]
Bij een testmelding is ons opgevallen dat een Buisleiding gevaarlijke inhoud zonder dat daar een EV aan hangt door de validatie is gekomen bij het Kadaster. Het lijkt ons vanzelfsprekend dat dit niet mogelijk zou moeten zijn. Daarom hebben wij het verzoek dat bij een Buisleiding gevaarlijke inhoud wordt gecontroleerd of er een EV aan gekoppeld is bij het validatieproces. 

Hiermee voorkomen we dat er een Klic-melding afgehandeld kan worden, waarbij een BGI wordt geraakt, maar de grondroerder **geen** EV krijgt. Dit is wettelijk wel verplicht.

**Comment by herman-vandenberg** [comment]
Een netbeheerder heeft zelf alle mogelijkheden om er voor te zorgen dat er - door juist gebruik van de EV-beslissingsregels - een EV-maatregel wordt aangemaakt bij het thema _buisleidingGevaarlijkeInhoud_.
