### ISSUE TITLE
Unreferenced ExtraGeometrie in "Levering_18O000687_1"

### ISSUE THREAD

**Issue by nielsgerrits** [kadaster/klic-win#61]
Can someone confirm if the reference from Duct nl.imkl-TS1381.BGI_duct00001-p to ExtraGeometrie nl.imkl-TS1381.BGI_xg00001-d is correct? See GI_gebiedsinformatielevering_18O000687_1.xml line 1753.

Looks like ExtraGeometrie nl.imkl-TS1381.BGI_xg00001-p is not related to anything else. It is also not visible in Klic-viewer 4.3.0.0.

Duct nl.imkl-TS1381.BGI_duct00001-d relates to ExtraGeometrie nl.imkl-TS1381.BGI_xg00001-d.
Duct nl.imkl-TS1381.BGI_duct00001-f relates to ExtraGeometrie nl.imkl-TS1381.BGI_xg00001-f.
Duct nl.imkl-TS1381.BGI_duct00001-p relates to ExtraGeometrie nl.imkl-TS1381.BGI_xg00001-d. I think this is a typo.

File link:
https://github.com/kadaster/klic-win/blob/master/Uitleveren/Voorbeelden/Levering_18O000687_1.zip

Not sure if I should report this anyway and / or report it here so please be gentle. If I should report elsewhere please let me know. 

Thanks.

Edit: Same thing happens with nl.imkl-TS1392.BGI_xg00001-p, line 8290.

**Comment by herman-vandenberg** [comment]
The example 18O000687 is created by using test-accounts of KLIC (to be recognized as "bronhouder" TSxxxx). By using these test-accounts lots of special test-cases were handled to check whether our KLIC-software was working correct, even with situations which you wouldn't suspect in a 'normal' production situation. As such, the data you are looking at, is not originally delivered by a real asset-holder.

Let's zoom in to your remark.
The relation from Duct nl.imkl-TS1381.BGI_duct00001-p to ExtraGeometrie nl.imkl-TS1381.BGI_xg00001-d is indeed a typo.
Nevertheless the data is syntactically correct, according to the current version of IMKL v1.2.1.

**Comment by nielsgerrits** [comment]
Thanks for your answer.
