### ISSUE TITLE
VB2-VB6 fout in pngFormaat in JSON

### ISSUE THREAD

**Issue by richardhinkamp** [kadaster/klic-win#62]
Ik heb de voorbeeld VB2-VB6 door onze software laten inlezen en kwam vreemde dingen tegen, blijkt dat in de JSON de pngFormaat fout is. Er staat dit:

```
		"pngFormaat": {
			"omsluitendeRechthoek": {
				"Envelope": {
					"lowerCorner": {
						"value": [154692.0,
						389377.0]
					},
					"upperCorner": {
						"value": [155182.0,
						389639.0]
					},
					"srsName": "urn:ogc:def:crs:EPSG::28992",
					"srsDimension": 2
				}
			},
			"pixelsBreed": 6860,
			"pixelsHoog": 3668
		},
```
Maar dit moet zijn:
```
		"pngFormaat": {
			"omsluitendeRechthoek": {
				"Envelope": {
					"lowerCorner": {
						"value": [153622.0,
						389504.0]
					},
					"upperCorner": {
						"value": [154112.0
						389917.0]
					},
					"srsName": "urn:ogc:def:crs:EPSG::28992",
					"srsDimension": 2
				}
			},
			"pixelsBreed": 6860,
			"pixelsHoog": 5782
		},
```
De lowerCorner en upperCorner komen niet overeen met de juiste coordinaten, zie bijv de gebiedsinformatieLevering XML. De pixelsHoog komt niet overeen met de hoogte van de afbeeldingen. Dit maakt dat de voorbeelden niet goed bruikbaar zijn indien je deze data gebruikt.

PS. VB1 heeft geen JSON file, is dat bewust? Ons systeem begint bij de JSON normaal gesproken en kan VB1 dus niet verwerken.

**Comment by herman-vandenberg** [comment]
De coördinaten en de pixelsHoog in de LI_xxx.json (versie 1.2) komen inderdaad niet overeen met de gebiedsinformatieLevering XML en de meegeleverde kaarten.
VB1 is gebruikt als oorspronkelijke klassieke levering. Voor de volledigheid zal ook de JSON file van de betreffende levering worden toegevoegd (Levering_xxx.json; versie 1.5).
De voorbeelden worden z.s.m. geactualiseerd op GitHub.
