### ISSUE TITLE
PDF bijlage staat als bestandMediaType=PNG in JSON

### ISSUE THREAD

**Issue by richardhinkamp** [kadaster/klic-win#63]
_(Ik weet niet of dit de juiste plek is om dit te melden, ik hoor anders graag waar dat zou moeten.)_

Ik zie net twee leveringen waarbij de JSON uit de webservice een `themabijlagePerNetbeheerder` heeft met `bestandMediaType` PNG, maar het bestand is een PDF (zowel in de ZIP als de URL die vermeld staat in de JSON). Beide gevallen een soortBijlage=detailkaart. Indien gewenst kan ik doorgeven welke klicmeldingen/leveringen het zijn.

**Comment by FuatAkdeniz** [comment]
Beste Richard, we willen graag weten welke voorbeeld Klic-meldingen niet correct zijn. Je kan het mailen naar klic-win@kadaster.nl Alvast bedankt!
