### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Sander3003** [kadaster/klic-win#65]
This link is broken (form https://github.com/kadaster/klic-win/tree/master/B2B-koppeling%20beheerdersinformatie%20(BMKL%202.0)): https://github.com/kadaster/klic-win/blob/master/B2B-koppeling%20beheerdersinformatie%20(BMKL%202.0)/B2B-koppeling%20Aanleveren%20beheerdersinformatie%20(BMKL2.0)%202017-05-10.ppt

**Comment by herman-vandenberg** [comment]
Bedankt voor het signaleren.
De link is ondertussen hersteld!

**Comment by Sander3003** [comment]
Dank!
