### ISSUE TITLE
Onjuist gebruik van associatie naar andere features (heeftExtraInformatie, extraGeometrie)

### ISSUE THREAD

**Issue by herman-vandenberg** [kadaster/klic-win#66]
Nadat IMKL1.2 al breed was uitgerold, heeft een serviceprovider geconstateerd dat er in aanleveringen van netinformatie/beheerdersinformatie van netbeheerders onjuiste associaties werden gelegd.
Met name bij het element "heeftExtraInformatie" werd bij een aantal verschillende netbeheerders in veel gevallen een associatie gelegd naar _ExtraGeometrie_-features. Dit is onjuist. Deze associatie had vastgelegd moeten worden bij het element “extraGeometrie”.

Bij het aanleveren van (net)informatie wordt door KLIC niet gevalideerd of er een juiste associatie wordt gelegd tussen features.
Het aanscherpen van de validaties bij het aanleveren van (net)informatie door te controleren of er een correcte associatie wordt gelegd, heeft naar verwachting aanzienlijke gevolgen voor de performance.

**Comment by adam-ludera-intive** [comment]
New example of the same, incorrect, behaviour found in KLIC delivered today at 7:17 AM: 19G674322. 

The reference is from object nl.imkl-KL1011.MABS_Mantelbuis_pni_conduit_22052_366 (imkl:Mantelbuis) to object "nl.imkl-KL1011.EG_Mantelbuis_pni_conduit_22052_364" (imkl:ExtraGeometrie) by attribute imkl:heeftExtraInformatie, whilst should be imkl:extraGeometrie. 

Same issue applies to other ExtraGeometrie elements here, e.g. links to: 

- nl.imkl-KL1011.EG_Mantelbuis_pni_conduit_5460297_367
- nl.imkl-KL1011.EG_Mantelbuis_pni_conduit_5460308_352
- nl.imkl-KL1011.EG_Mantelbuis_pni_conduit_5460309_349
- etc.

And the same applies to KLIC 19G674323. I assume all KLIC that include data of this Utility Company will be the same.

**Comment by adam-ludera-intive** [comment]
Same applies to KLIC: 19G674242 link to: nl.imkl-KL1040.EG_IMKL_TechnischGebouw__Stationinrichting_Elektra_LS__515686096_114385253

**Comment by adam-ludera-intive** [comment]
KLIC: 19G674299 link to: nl.imkl-KL1011.EG_Mantelbuis_pni_conduit_5553728_203

**Comment by adam-ludera-intive** [comment]
KLIC: 19G674290, link to: nl.imkl-KL1040.EG_IMKL_TechnischGebouw__Station_Gebouw_LD__380036948_114312871

**Comment by adam-ludera-intive** [comment]
KLIC: 19G674270, link to: nl.imkl-KL1040.EG_IMKL_TechnischGebouw__Stationinrichting_Elektra_LS__806838063_114395619

**Comment by herman-vandenberg** [comment]
If this concerns recent KLIC -requests, this means that the relevant network operators have still **not adjusted** their software.
We will analyze this further and ask attention to this by network operators (KL1011, KL1040).

**Comment by herman-vandenberg** [comment]
Some time ago we asked the network operator the status of this issue. He answered as follows:

"Inmiddels heeft _serviceprovider_ ons laten weten dat er geen losse patch mogelijk is voor issue https://github.com/kadaster/klic-win/issues/66 en dat correctie alleen mogelijk is door een upgrade naar de nieuwste versie. Deze software upgrade hebben we gepland in Mei 2020 door te voeren op productie ..."
