### ISSUE TITLE
Inconsistent xlink:href link definition accross Production KLICs

### ISSUE THREAD

**Issue by adam-ludera-intive** [kadaster/klic-win#68]
There are two approaches in how xlink:href are defined in Production KLICs. This makes the processing of those KLICs inconsistent with many connections or attributes being broken.

one:
`<net:inNetwork xlink:href="nl.imkl-KL1011.UNET_telecommunications_1">`
with the "xlink" defined in general scope, in the beginning of the file as:
`xmlns:xlink="http://www.w3.org/1999/xlink"`

second:
`<net:inNetwork xmlns:n1="http://www.w3.org/1999/xlink" n1:href="nl.imkl-KL1051.geulen">`

Sample KLIC Number: 19G457749

**Comment by FuatAkdeniz** [comment]
We controleren niet of de netbeheerder zich houdt aan de aanbeveling om voorgedefinieerde afkorting voor namespaces te gebruiken. De netbeheerder is hier reeds op gewezen.
