### ISSUE TITLE
Question: 2.2 Delivery as subsequent Partial Delivery to 2.1

### ISSUE THREAD

**Issue by adam-ludera-intive** [kadaster/klic-win#69]
Could you please clarify if it is valid to expect that there can be a situation where a KLIC that was delivered as Partial Delivery in version 2.1, after the Go-Live will be delivered, as another Partial Delivery or Complete Delivery, in version 2.2? 

Or rather we shall expect that the following deliveries will be still 2.1, including the Complete Delivery?

**Comment by herman-vandenberg** [comment]
At this moment it is NOT our intention - after switching to version 2.2 - to check whether there has already been an earlier delivery for this request with an older version (i.c. version 2.1).
So, in potential it is possible that there will be partial deliveries in version 2.1 and newer deliveries in version 2.2. However, this will normally only involve very small number of deliveries.
