### ISSUE TITLE
H 3.2.2 Zoeken naar gebiedsaanvragen XML response bevat onnodige elementen

### ISSUE THREAD

**Issue by alex3305** [kadaster/klic-win#7]
In de API specificatie onder hoofdstuk 3.2.2 staat een voorbeeld XML response. Wij denken dat er in deze XML response het element `<element>` onnodig voorkomt. Daarom zouden wij voorstellen deze te laten vervallen en het volgende aan te houden:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<gebiedsInformatieAanvragen> 
      <gebiedsInformatieAanvraag href="https://api.kadaster.nl/klic/v1/ws/gebiedsInformatieAanvraag/2a3fe3ef-b606-4f6a-b5dd-d19d6f3e3ce6/Netbeheerder" />
      <gebiedsInformatieAanvraag href="https://api.kadaster.nl/klic/v1/ws/gebiedsInformatieAanvraag/995b3a08-de6a-44f1-8547-98273f1139bb/Netbeheerder" />
</gebiedsInformatieAanvragen>
```

Naar onze mening wordt tevens de semantiek van het response verbeterd, waarnaast de implementeerbaarheid vereenvoudigd wordt.

**Comment by martinborgman** [comment]
Het `<element>` element moet inderdaad weg.
Dit wordt aangepast in de volgende versie van het document.

**Comment by martinborgman** [comment]
Is gefixed in versie 0.76
