### ISSUE TITLE
Missing elements of  19O000151 and L19O000152

### ISSUE THREAD

**Issue by szmucha** [kadaster/klic-win#71]
The artificial klics doesn't contains followed elements: 
heeftExtraInformatie association in objects: Elektriciteitskabel, Kabelbed, Mangat, Overig, Rioolleiding, Telecommunicatiekabel, ThermischePijpleiding, Toren, Waterleiding 

EigenTopografie - no example of Topo layer per UC company (lack of Belanghebbende association)

Missing statuses: 
Telecommunicatiekabel: Projected, Disused 
Rioolleiding: Projected, Disused 
Waterleiding: Projected, Disused 
ThermischePijpleiding: Projected, Disused
Overig: Projected, Disused

**Comment by herman-vandenberg** [comment]
From a test perspective, it was not considered necessary to implement associations or statuses for all object types. In our situation, the technical solution has a generic character and therefore not all variations have to be tested.
From an external perspective this is of course a bit more nuanced. We consider supplementing the test set with the missed test situations.

**Comment by FuatAkdeniz** [comment]
TCS KLIC 25 november 2022:
Dit is geen aanpassing voor de KLIC-standaarden, wel een verbeterpunt voor een volgende upgrade van de standaarden.
Samen met de netbeheerders zorgen we voor representatieve datasets.

Issue zal gesloten worden.
