### ISSUE TITLE
Attachment (Bijlage) as external Link

### ISSUE THREAD

**Issue by adam-ludera-intive** [kadaster/klic-win#72]
The BestandLocatie child element of the Bijlage (and the inherited types) is defined as URI and thus we expect that this can also contain a link to an external resource, most likely via http or ftp request. 

Firstly, is this a correct assumption?

Secondly, could you please provide an example of how such a link would look like? Most preferably as a KLIC and if not possible for now - a code snippet at least.

**Comment by herman-vandenberg** [comment]
For objects of the type _Bijlage_ and _ExtraDetailinfo_, a reference is made to a file that is included in the delivery (zip file). It is currently NOT foreseen that references can be made to an external resource.
Example in GI.xml:

`
<imkl:bestandLocatie>bronnen/KL9999/nl.imkl-KL9999_19G558958.WarmteStad_ALG_b2e742b9.pdf</imkl:bestandLocatie>
`
