### ISSUE TITLE
Duplicate Belang-s

### ISSUE THREAD

**Issue by adam-ludera-intive** [kadaster/klic-win#73]
There are numerous real KLICs where there would be two or more Belang elements for the same set of Disciplines for the same Utility Company. 

In many cases, they are also carrying very similar or exactly the same contact information.

One of such examples would be 19G632000:
  ```
<imkl:geraaktBelangBijGraafpolygoon xlink:href="nl.imkl-KL1082._Belang_5012126-101"/>
<imkl:geraaktBelangBijGraafpolygoon xlink:href="nl.imkl-KL1082._Belang_5010619-402"/>
```

This seems then redundant to return such information to the end consumer - they have no way of knowing if one Belang applies to a specific part of the network, let alone having any advantage of seeing the same contact twice.

Shouldn't this be validated on input by UC or when consolidated into KLIC? Should there be a solid rationale behind having such duplicated Belang - how should we assist the end consumer knowing which Belang data relates to the part/element of the network that they are interested in?

**Comment by herman-vandenberg** [comment]
In the "gebiedsinformatieLevering" for all networkoperators with interest in the requested area, all “Belang”-features with geometric overlap with the requested area are taken over literally.
This can indeed mean that the same contact information is delivered more than once.

It is up to (the system of) the user to handle/present this information in a handy way.
Currently, the standardization committee has not made any agreements to deduplicate contact details in the delivery.

As you can discover, the contact information is deduplicated in our KLIC delivery letter.
