### ISSUE TITLE
Mantelbuis with link to a missing Utility Link

### ISSUE THREAD

**Issue by adam-ludera-intive** [kadaster/klic-win#75]
In KLIC 19G674299 there is a Mantelbuis nl.imkl-KL1088.Mantelbuis-1786 with following link to it's geometry (provided as UL, following the data model):

`<net:link xlink:href="nl.imkl-KL1088.Mantelbuis_leeg-"></net:link>`

There is however no element with GML ID "nl.imkl-KL1088.Mantelbuis_leeg-" in this KLIC.

**Comment by herman-vandenberg** [comment]
We will inform the network-operator.
