### ISSUE TITLE
Clarifications: Format of the Attachments

### ISSUE THREAD

**Issue by adam-ludera-intive** [kadaster/klic-win#78]
Based on all examples so far we see all Utility Company Attachments are delivered as PDFs. Can this be then taken as a rule, i.e. that all attachments delivered in KLIC (i.e. files pointed by Bijlage, EisVoorzorgsmaatregelBijlage, and ExtraDetailInfo) will always be of type PDF?

The fact is that the BestandMediaType attribute, based on the enumeration of BestandMediaTypeValue, can be delivered with the following values. However, as said previously, we have never seen those in any production KLICs nor samples from GitHub.
1. JPEG
2. TIFF
3. PDF
4. PNG
5. XML
6. JSON

**Comment by herman-vandenberg** [comment]
At the moment,  network operators can only provide PDF-type attachments.
It is not foreseen that this will change in the near future.
The KLIC-delivery itself of course also includes documents of the PNG type (delivery version 2.1, background layer), and XML.

**Comment by adam-ludera-intive** [comment]
Thank you for your answer. 

One additional question regarding attachments. Is it guaranteed that all Attachments' file names will be unique in the scope of one KLIC?

**Comment by herman-vandenberg** [comment]
The filenames of attachements are based on it's identifier `bestandIdentificator` as mentioned in _Bijlage_ or _ExtraDetailinfo_.  As this identifiers are unique, their filenames will be unique too.
We also take care that attachements which ar build by KLIC itself, will have a unique filename.
So we can ensure their uniqeness within the scope of one KLIC-request.
Take care:
It is possible that an attachement as refered more than once (e.g. an attachement of the type 'huisaansluiting' refered by more ExtraDetailinfo-addresses).
