### ISSUE TITLE
ExtraDetailInfo outside of bounding box

### ISSUE THREAD

**Issue by adam-ludera-intive** [kadaster/klic-win#79]
In KLIC 19G642089 we find ExtraDetailInfo elements to be outside of bounding box. This should not be the case.

Bounding box:
`<gml:boundedBy>
            <gml:Envelope srsName="urn:ogc:def:crs:EPSG::28992" srsDimension="2">
                <gml:lowerCorner>121861.0 487206.0</gml:lowerCorner>
                <gml:upperCorner>121917.0 487242.0</gml:upperCorner>
            </gml:Envelope>
</gml:boundedBy>`

ExtraDetailInfo:
`<imkl:ligging>
	<gml:Point gml:id="nl.imkl-KL1088.ExtraDetailinfo-00000707.pdf-119919-0" srsDimension="2" srsName="EPSG:28992">
		<gml:pos>121918 487213</gml:pos>
	</gml:Point>
</imkl:ligging>`

**Comment by herman-vandenberg** [comment]
Unfortunately the specified KLIC-request has expired, so we don't have the network-information any longer on our systems (as Kadaster we may not same this information). Therefore we requested this KLIC again with the same parameters.
When doing this, we were already warned that the requested information about "huisaansluiting" on this specific address is outside the polygon (graafpolygoon). See:

![image](https://user-images.githubusercontent.com/34309957/72735795-d2745e00-3b9c-11ea-817e-9379a58ff2af.png)

It should be noticed that it is not forbidden to request "huisaansluiting"-documents for addresses outside the selected polygon.
Also, network-information supplied by decentralized network operators is NOT checked whether it is within the requested area.

Below is confirmed that in this case it's possible to have geometry-elements outside the polygon and even the bounding box:
![image](https://user-images.githubusercontent.com/34309957/72738119-34cf5d80-3ba1-11ea-8f94-f0a07ce3a1cc.png)
