### ISSUE TITLE
H 3.3.2 / 4.2.3 @-elementen in JSON response verminderd semantiek

### ISSUE THREAD

**Issue by alex3305** [kadaster/klic-win#8]
In de verschillende JSON responses worden er @-elementen gebruikt om waarschijnlijk de vertaalslag te maken van XML attributen naar JSON elementen. Echter vermindert hierdoor de semantiek van het document. Ook wordt het geautomatiseerd verwerken met een API-client implementatie van deze JSON elementen lastiger. Tevens kunnen in zowat alle gevallen de geneste elementen direct als waarde van de bovenliggende key worden gebruikt. Voorbeeld:

Huidige situatie:

``` json
"aanvraagSoort": {"@href": "https://api.kadaster.nl/klic/v1/cl/aanvraagSoorten/orientatiemelding"}
```

Voorgestelde situatie:

``` json
"aanvraagSoort": "https://api.kadaster.nl/klic/v1/cl/aanvraagSoorten/orientatiemelding"
```

**Comment by martinborgman** [comment]
Dit komt uit een presentatie van Les Hazlewood [Design Beautiful REST + JSON APIs](https://newcircle.com/s/post/1526/beautiful_rest_and_json_apis_les_hazelwood_video) | [slides](http://www.slideshare.net/stormpath/rest-jsonapis).
We bespreken dit even intern.

**Comment by martinborgman** [comment]
Is gefixed in versie 0.76
