### ISSUE TITLE
Duplicated Annotation elements

### ISSUE THREAD

**Issue by adam-ludera-intive** [kadaster/klic-win#82]
In KLIC: 20G129229
Annotations are duplicated - their metadata and geometries are exactly the same.

For example please see Annotations with GML Ids:
1. nl.imkl-KL1040.ANNO_IMKL_Annotatie__PIBI_Lijn__655367890_11339250
2. nl.imkl-KL1040.ANNO_IMKL_Annotatie__PIBI_Lijn__655367894_11339249

**Comment by adam-ludera-intive** [comment]
The same is found, in that KLIC, for Measurements. Geometry, rotation and all metadata fully duplicated.

For example:
1. nl.imkl-KL1040.MAAT_IMKL_Maatvoering__Maatvoering_hld_pijl_gd__943621805_92738701
2. nl.imkl-KL1040.MAAT_IMKL_Maatvoering__Maatvoering_hld_pijl_gd__943621866_92738700

**Comment by herman-vandenberg** [comment]
In the last example, there is a difference between the  _Maatvoering_-objects that you mention; consecutively:

`	<imkl:rotatiehoek uom="urn:ogc:def:uom:OGC::deg">-64</imkl:rotatiehoek>`

`	<imkl:rotatiehoek uom="urn:ogc:def:uom:OGC::deg">-153</imkl:rotatiehoek>`

**Comment by herman-vandenberg** [comment]
We checked the original delivery of this network-operator.
Both _Annotatie_-objects were mentioned here, so the KLIC-process works correct.
We will inform the network-operator (KL1040).
See attachment: 
[Annotaties.pdf](https://github.com/kadaster/klic-win/files/4275925/Annotaties.pdf)

**Comment by vanderbergh** [comment]
Hoi
dank voor de melding. Klic proces werkt goed.
dubbelle objecten bekeken
1) maatvoering pijlen zijn correct dubbel opo zelfde coordinaat echter hebben ander rotatiehoek
2)maatvoering maatlijnen kunnen deels op elkaar liggen. en zo is de model binnen ons Gis systeem. Bv voetmaat 6 meter uit gevel is maatlijn en voetmaat 8 meter is ook maatlijn.
3)de lege mantelbuis in profielbakjes wordt idd dubbel aangeleverd als annotatie. Dit gaan we oplossen en zal in een volg release meegaan.
Gr Hendrik Liander
