### ISSUE TITLE
inNetwork 1:N relation in klics

### ISSUE THREAD

**Issue by szmucha** [kadaster/klic-win#86]
We are experiencing delivery of the klics which contains 1:N relation between cable and Network. Particular example klics: 20G158360; 20G158610; Utility Company: KL0004. 

The general case has been described and discussed here: https://github.com/Geonovum/imkl2015-review/issues/269 but I believe that as nothing regarding the model will be updated short term, the validation would be helpful.

**Comment by herman-vandenberg** [comment]
@szmucha We will analyse these KLIC-requests and consider your suggestion. You will hear from us.

**Comment by herman-vandenberg** [comment]
@szmucha We analyzed KLIC-request 20G158360 and confirm your conclusion about the 1:N relationship. This is not according to the work-around which was agreed by the technical committee and confirmed by KGO/BAO. See [#181](https://github.com/Geonovum/imkl2015-review/issues/181.)
We have forwarded the analysis to the relevant network operator and urgently requested to take action as soon as possible.

**Comment by szmucha** [comment]
@herman-vandenberg did you received any feedback on this?

**Comment by herman-vandenberg** [comment]
@szmucha 
After asking again,  we have just got feedback from the service provider of the relevant network operator:
"The issues were discussed with the network operator and we are still waiting for an agreement to be allowed to carry out the work. If there is an agreement, we will first realize this on the test environment before going to production."

**Comment by FuatAkdeniz** [comment]
TSC KLIC 25 november 2022:
Dit is behandeld in issue https://github.com/Geonovum/imkl2015-review/issues/269 en zal derhalve gesloten worden.
