### ISSUE TITLE
KL1051 data doesn't contain "Telecommunicatiekabel"

### ISSUE THREAD

**Issue by szmucha** [kadaster/klic-win#87]
On the number of klics (~300 verified) there is no Telecommunicatiekabel objects for KL1051 - which provides mainly the datatransport I think - just "Kabelbeds" and "Mantelbuises" which I believe doesn't provide all the data about cables. So my question is if this is right? 

I can imagine the situation that there is only "Kabelbed" without Cable inside - but I haven't found even single case with Cable inside.

**Comment by szmucha** [comment]
And sample klics where I've found this situation: 
"19G468490"
"19G469551"
"19G540023"
"19G606450"
"19G660236"
"20C006611"
"20C006612"
"20C007347"
"20C008148"
"20C008287"
"20C008410"
"20C009931"
"20C009933"
"20C009934"
"20C010928"
"20C010938"
"20G000101"
"20G006480"
"20G034307"
"20G038222"
"20G049619"
"20G064502"
"20G072932"
"20G107941"
"20G114638"
"20G119864"
"20G119984"
"20G129284"
"20G129374"
"20G129379"
"20G130003"
"20G132041"
"20G133306"
"20G133401"
"20G134297"
"20G134349"
"20G134376"
"20G135476"
"20G136192"
"20G136305"
"20G136406"
"20G136452"
"20G137964"
"20G138092"
"20G138470"
"20G138699"
"20G138778"
"20G139060"
"20G140003"
"20G141489"
"20G142942"
"20G149994"
"20G158360"
"20G164847"
"20G164963"
"20G165531"
"20G169601"
"20G169605"
"20G169608"
"20G169609"
"20G169611"
"20G169614"
"20G169615"
"20G169616"
"20G169617"
"20G171630"
"20G174885"
"20G176306"
"20G179005"
"20G181291"
"20G181301"
"20G181303"
"20G181304"
"20G181306"
"20G181308"
"20G181312"
"20G181316"
"20G181320"
"20G181325"
"20G181326"
"20G181329"
"20G181331"
"20G181334"
"20G181336"
"20G181338"
"20G181341"
"20G181342"
"20G181343"
"20G181345"
"20G181346"
"20G181350"
"20G181352"
"20G181353"
"20G181355"
"20G181358"
"20G181360"
"20G181369"
"20G181371"
"20G181376"
"20G181377"
"20G181379"
"20G187912"
"20G190639"
"20G190714"
"20G191731"
"20G199672"
"20G200297"
"20G201672"
"20G202047"
"20G202051"
"20G202053"
"20G202057"
"20G202257"
"20G202258"
"20G202335"
"20G202343"
"20G202377"
"20G202399"
"20G202402"
"20G202408"
"20G202440"
"20G202445"
"20G202446"
"20G202453"
"20G202454"
"20G202457"
"20G202463"
"20G202464"
"20G202465"
"20G202466"
"20G202469"
"20G202473"
"20G202475"
"20G202476"
"20G202478"
"20G202481"
"20G202482"
"20G202485"
"20G202486"
"20G202489"
"20G202491"
"20G202494"
"20G202497"
"20G202515"
"20G202522"
"20G202524"
"20G202525"
"20G202528"
"20G202536"
"20G202542"
"20G202550"
"20G202551"
"20G203273"
"20G212010"
"20G217088"
"20G218414"
"20G218416"
"20G218420"
"20G219972"
"20G226298"
"20G230904"
"20G231561"
"20G231578"
"20O021510"
"20O021519"
"20O024439"
"20O024856"
"20O026390"
"20O028080"
"20O029878"
"20O029881"
"20O033271"
"20O033274"

**Comment by herman-vandenberg** [comment]
@szmucha I completely understand your confusion.
This type of implementation is not what you would suspect, but is accepted by the sector and is mainly used by telecom-providers. The telecommunication-cables (which can be hundreds and more) are bundled and then defined als "Kabelbed" with an obligated attribute "aantalKabelsLeidingen". The solitair "Telecommunicatiekabel" is not used in this situation...
