### ISSUE TITLE
BMKL: relatienummer alleen van toepassing bij Aanvrager

### ISSUE THREAD

**Issue by herman-vandenberg** [kadaster/klic-win#89]
Bij een GET gebiedsinformatieAanvragen wordt bij zowel een _Aanvrager_, als een _Opdrachtgever_ (optioneel) een relatienummer terug gegeven.
Dit is niet mogelijk en functioneel onjuist. Een opdrachtgever is geen bekende relatie van Kadaster-KLIC en heeft geen relatienummer.
De consequentie lijkt me nihil, immers dit nummer wordt nu toch al nooit teruggegeven.

**Comment by JustinRoodenburg** [comment]
**Toelichting op implementatie van het Kadaster**:
Het modelschema in de SWAGGER-UI is aangepast.
Als je als afnemer er rekening mee hield dat er een relatienummer teruggegeven kon worden bij de oprachtgever, kan deze code daar nu op aangepast worden.

Voor een compleet overzicht en voorbeelden van de BMKL-API versie 2.1 zie onderstaande links:
De nieuwe versie van het berichtenmodel (BMKL versie 2.1) vindt u op [deze GitHub pagina van het Kadaster](https://github.com/kadaster/klic-win/tree/master/BMKL).
Een toelichting op en en voorbeelden van de wijzigingen van de BMKL-standaarden vindt u op [deze GitHub pagina van het Kadaster](https://github.com/kadaster/klic-win/blob/master/Toekomstige%20wijzigingen/Toelichting%20specifieke%20onderwerpen/Implementatie%20upgrade%20KLIC%20standaarden/Gewijzigde%20BMKL.md).
