### ISSUE TITLE
H 3.3.2 / 4.2.3 Tijden hebben te hoge precisie

### ISSUE THREAD

**Issue by alex3305** [kadaster/klic-win#9]
In de datum en tijd van de responses in paragrafen 3.3.2 en 4.3.2 is de precisie aan de onnodig hoge kant. Onze voorkeur zou hebben om dit op de seconde af te handelen.

**Comment by martinborgman** [comment]
De nauwkeurigheid is inderdaad wat er hoog. Ik zie ook dat niet overal dezelfde notatie gebruikt wordt.
Dit wordt aangepast in de volgende versie van het document.

**Comment by martinborgman** [comment]
Is gefixed in versie 0.76
