### ISSUE TITLE
Aanpassing naamgeving statussen bij samenstellen beheerdersinformatie

### ISSUE THREAD

**Issue by herman-vandenberg** [kadaster/klic-win#90]
De invoering van IMKL/BMKL stond in najaar 2018 flink onder druk. Het was niet meer mogelijk om een logische naam te geven voor de eindstatus als de nieuwe processtap om beheerdersinformatielevering samen te stellen, was afgerond. Daardoor heeft de eindstatus nu een onlogische naam. 
In de nieuwe versie van de BMKL-API zou dit rechtgetrokken kunnen worden.

Zie het voorgestelde statusverloop in de bijlage:
[klc-STD Produceren beheerdersinformatie (codelist v2).pdf](https://github.com/kadaster/klic-win/files/4655780/klc-STD.Produceren.beheerdersinformatie.codelist.v2.pdf)

Samengevat:

status | huidige naam | gewenste naam
-- | -- | --
beheerdersinformatie   is gereed om deze te laten samenstellen ("bundelen") tot een   gebiedsinformatie | biGereedVoorLevering | biGereedVoorSamenstellen
er is   een levering van beheerdersinformatie (zipbestand) samengesteld voor de   netbeheerder | biGereedVoorSamenstellenProduct | biLeveringSamengesteld

**Comment by herman-vandenberg** [comment]
In bovengenoemd statusdiagram (STD) worden ook enkele attribuutnamen genoemd van datumtijdstippen bij een bepaalde status. Bij de nieuwe status `biGereedVoorSamenstellen` staat als datumtijdstip `datumBeheerdersinformatieOntvangen`.
Het moment `datumBeheerdersinformatieOntvangen` is echter het moment van ontvangst van beheerdersinformatie. Dit moment wordt vastgelegd in deze variabele. Vervolgens worden nog enkele processtappen doorlopen (waaronder valideren van aangeleverde informatie) voordat een gevalideerde en correcte aanlevering van beheerdersinformatie gereed is voor samenstellen (bundelen tot gebiedsinformatie). 
Het datumtijdstip dat een levering geschikt is voor samenstellen is dus niet het moment dat de beheerdersinformatie is ontvangen, maar wel de status dat de 'datumBeheerdersinformatieOntvangen' wordt teruggegeven in de betreffende BMKL-API (/gebiedsinformatieAanvragen/{giAanvraagId}/beheerdersinformatieAanvragen/{biAanvraagId}/beheerdersinformatieLevering).
Het datumtijdstip 'datumBILeveringSamengesteld` is een moment dat in het productieproces van KLIC wordt bijgehouden, maar niet wordt teruggegeven in een API.

Om verwarring te voorkomen, laat ik hieronder een plaatje zien van statussen / datumtijdstippen die met de BMKL-API worden teruggegeven (ook het verbindingslijntje voor `datumBeheerdersinformatieOntvangen` is weggehaald):
![image](https://user-images.githubusercontent.com/34309957/87036493-2f1b1200-c1eb-11ea-87cd-ece5489b7e16.png)

**Comment by JustinRoodenburg** [comment]
**Toelichting op implementatie van het Kadaster**:
Er zijn aangepaste waarden in de waardelijst voor `biProductieStatus`. Deze is zichtbaar voor zowel Centrale als Decentrale netbeheerders.
Tevens wordt er gebruik gemaakt van een gewijzigde URI. (zie issue [#94](https://github.com/kadaster/klic-win/issues/94) )

Voor een compleet overzicht van de toegestane waarden, zie de waardelijst op:
https://api.klic.kadaster.nl/waardelijsten/v2/biProductieStatussen/

Voor een compleet overzicht en voorbeelden van de BMKL-API versie 2.1 zie onderstaande links:
De nieuwe versie van het berichtenmodel (BMKL versie 2.1) vindt u op [deze GitHub pagina van het Kadaster](https://github.com/kadaster/klic-win/tree/master/BMKL).
Een toelichting op en en voorbeelden van de wijzigingen van de BMKL-standaarden vindt u op [deze GitHub pagina van het Kadaster](https://github.com/kadaster/klic-win/blob/master/Toekomstige%20wijzigingen/Toelichting%20specifieke%20onderwerpen/Implementatie%20upgrade%20KLIC%20standaarden/Gewijzigde%20BMKL.md).
