### ISSUE TITLE
BMKL: refereer in GebiedsinformatieAanvraag naar bestaande IMKL-waardelijsten

### ISSUE THREAD

**Issue by herman-vandenberg** [kadaster/klic-win#91]
In de BMKL-API voor het opvragen van een _GebiedsinformatieAanvraag_ wordt bij een tweetal attributen niet verwezen naar een bestaande IMKL-waardelijst. Dit zijn de IMKL-waardelijsten voor:
- `aanvraagSoort`
- `soortWerkzaamheden`

Maak hergebruik van deze bestaande lijsten.

Voorbeeld huidige situatie:
`  "aanvraagSoort": "https://api.kadaster.nl/klic/v1/cl/aanvraagSoorten/graafmelding"`
`  "soortWerkzaamheden": [
"https://api.kadaster.nl/klic/v1/cl/soortWerkzaamheden/heien"
]`

Voorbeeld gewenste situatie:
`  "aanvraagSoort": "http://definities.geostandaarden.nl/imkl2015/id/waarde/AanvraagSoortValue/graafmelding"`
`  "soortWerkzaamheden": [
"http://definities.geostandaarden.nl/imkl2015/id/waarde/SoortWerkzaamhedenValue/heien"
]`

**Comment by JustinRoodenburg** [comment]
**Toelichting op implementatie van het Kadaster**:
In de BMKL-API versie 2.1 wordt er gebruik gemaakt van een gewijzigde URI (zie ook issue [#94](https://github.com/kadaster/klic-win/issues/94) ) voor `aanvraagSoort` en `soortWerkzaamheden` (zie ook issue [#64](https://github.com/kadaster/klic-win/issues/64) ).

Voor een compleet overzicht van de toegestane waarden, zie de waardelijst op:
https://register.geostandaarden.nl/waardelijst/imkl/2.0.0/IMKL-Waardelijsten-2.0.xml

Voor een compleet overzicht en voorbeelden van de BMKL-API versie 2.1 zie onderstaande links:
De nieuwe versie van het berichtenmodel (BMKL versie 2.1) vindt u op [deze GitHub pagina van het Kadaster](https://github.com/kadaster/klic-win/tree/master/BMKL).
Een toelichting op en en voorbeelden van de wijzigingen van de BMKL-standaarden vindt u op [deze GitHub pagina van het Kadaster](https://github.com/kadaster/klic-win/blob/master/Toekomstige%20wijzigingen/Toelichting%20specifieke%20onderwerpen/Implementatie%20upgrade%20KLIC%20standaarden/Gewijzigde%20BMKL.md).
