### ISSUE TITLE
NTD Klic Viewer 

### ISSUE THREAD

**Issue by bart-thevis** [kadaster/klic-win#93]
Zowel de BIL uit de NTD en de Kadaster Klic Viewer geschikt maken voor gebruik icm de NTD.

**Comment by FuatAkdeniz** [comment]
Beste Bart, dit is in het KGO KLIC besproken. Het Kadaster zal de mogelijkheden onderzoeken.

**Comment by FuatAkdeniz** [comment]
Met Release van 26 mei is dit mogelijk geworden.  https://github.com/kadaster/klic-win/blob/master/KLIC%20-%20Geplande%20werkzaamheden.md#planning-voor-release---26-mei-2021

**Comment by FuatAkdeniz** [comment]
@bart-thevis Kan je dit sluiten?

**Comment by bart-thevis** [comment]
Ik geloof je op je woord ;-) Thnx!
