### ISSUE TITLE
Toepassen nieuwe hostname/base-url voor KLIC-API's

### ISSUE THREAD

**Issue by herman-vandenberg** [kadaster/klic-win#94]
Het Kadaster heeft een nieuwe richtlijn uitgegeven voor de naamgeving van de 'hostname' voor door Kadaster beheerder API's. Voor KLIC zou dit betekenen dat KLIC-API's worden gehost op:
`https://api.klic.kadaster.nl`.
Daarnaast is het gewenst om de "base-url", het pad dat gebruikt wordt na de hostname voor de verschillende API-diensten binnen KLIC, ook te vereenvoudigen en te uniformeren.
Daarbij willen we wél de gedragsregels zoals deze beschreven zijn als nationale API-richtlijn (en toegepast bij o.a. DSO) respecteren.
In later commentaar volgt een overzicht van de momenteel gebruikt paden en de voorgestelde nieuwe paden voor de verschillende API-endpoints.

**Comment by herman-vandenberg** [comment]
Kadaster heeft de intentie om breed gebruik te maken van een API-portal.
Aangezien op deze API-portal momenteel nog niet de authenticatie/autorisatie-instellingen geïmplementeerd zijn die we voor KLIC nodig hebben, gebruiken we voor deze diensten eerst nog het "service10"-toegangspad.
Voor het opvragen van KLIC-waardelijsten gaat al wél van de portal gebruik gemaakt worden.
Zie hieronder:
![image](https://user-images.githubusercontent.com/34309957/98241661-8d72ba00-1f6b-11eb-85e5-403410f783ce.png)

**Comment by JustinRoodenburg** [comment]
De endpoints van versie 2 worden gecommuniceerd op de Kadaster Github van KLIC: 
https://github.com/kadaster/klic-win/blob/master/API%20management/Overzicht%20endpoints%20KLIC%20APIs.md
