### ISSUE TITLE
Eenduidigheid in naamgeving status beheerdersinformatie ("bi") en gebiedsinformatie ("gi")

### ISSUE THREAD

**Issue by herman-vandenberg** [kadaster/klic-win#95]
De naamgeving voor de statussen voor aanleveringen zijn snel en duidelijk herkenbaar aan hun prefix:
- voor netinformatie: prefix "ni"
- voor documenten: prefix "doc"
- voor beheerdersinformatie: prefix "bi"

Het is de bedoeling geweest om deze conventie ook door te voeren bij de verschillende statussen voor het afhandelen van beheerdersinformatie en gebiedsinformatie, respectievelijk:
- notificeren en produceren beheerdersinformatie: prefix "bi"
- afhandelen gebiedsinformatie: prefix "gi"

Vanwege tijdsdruk voor implementatie van IMKL (najaar 2018) kon deze laatste wijziging niet op tijd worden doorgevoerd. Verzoek is om deze eenduidigheid alsnog door te voeren.
Zie onderstaande statussen in groen kader.
![image](https://user-images.githubusercontent.com/34309957/85399868-cf203c80-b557-11ea-8cf9-ab5ad32d5cf8.png)

**Comment by JustinRoodenburg** [comment]
**Toelichting op implementatie van het Kadaster**:
Er zijn aangepaste waarden in de waardelijst volgens het overzicht hierboven.
Tevens wordt er gebruik gemaakt van een gewijzigde URI. (zie issue [#94](https://github.com/kadaster/klic-win/issues/94) )

Voor een compleet overzicht van de toegestane waarden, zie de waardelijsten op:
https://api.klic.kadaster.nl/waardelijsten/v2/aanleverStatussen
https://api.klic.kadaster.nl/waardelijsten/v2/biNotificatieStatussen/
https://api.klic.kadaster.nl/waardelijsten/v2/biProductieStatussen/
https://api.klic.kadaster.nl/waardelijsten/v2/giAanvraagStatussen/



Voor een compleet overzicht en voorbeelden van de BMKL-API versie 2.1 zie onderstaande links:
De nieuwe versie van het berichtenmodel (BMKL versie 2.1) vindt u op [deze GitHub pagina van het Kadaster](https://github.com/kadaster/klic-win/tree/master/BMKL).
Een toelichting op en en voorbeelden van de wijzigingen van de BMKL-standaarden vindt u op [deze GitHub pagina van het Kadaster](https://github.com/kadaster/klic-win/blob/master/Toekomstige%20wijzigingen/Toelichting%20specifieke%20onderwerpen/Implementatie%20upgrade%20KLIC%20standaarden/Gewijzigde%20BMKL.md).
