### ISSUE TITLE
extra thema Waterstofgas

### ISSUE THREAD

**Issue by yvon788** [kadaster/klic-win#96]
1 Op dit moment worden er diverse pilotprojecten vanuit netbeheerders gestart (o.a. Stedin) om in bestaande gasleidingen het medium waterstofgas te laten stromen. Als grondroerder is het belangrijk om dit te weten.
2 Mogelijk naar de toekomst worden er ook 'waterstofleidingen' nieuw aangelegd.
Voor de grondroerder is het belangrijk dat er een nieuw thema waterstofgas komt, en dat bekend is dat door bestaande gasleidingen het medium waterstof stroomt.

**Comment by Marijnbiekart** [comment]
https://inspire.ec.europa.eu/codelist/OilGasChemicalsProductTypeValue bevat al de waarde 'hydrogen'

**Comment by herman-vandenberg** [comment]
In het overleg van de TCS is bovenstaand onderwerp aan de orde geweest.
In termen van objectklassen hoort een waterstofleiding tot de objectklasse _OilGasChemicalsPipe_ (INSPIRE) / _OlieGasChemicalienPijpleiding_ (IMKL ) met het producttype `hydrogen` (zoals ook aangegeven door Marijn Biekart). Dit producttype is door het TCS inderdaad vertaald naar `waterstof`.
Namens het TCS is door Hans Postema en Wil Lambo uitgezocht onder welk IMKL-thema 'waterstofleidingen' geplaatst moeten worden. Door hen is aangegeven dat een waterstofleiding valt onder het IMKL-thema `buisleidingGevaarlijkeInhoud`, **mits** wordt voldaan aan een aantal voorwaarden zoals aangegeven in het Revb (o.a. minimum diameter en druk).
![image](https://user-images.githubusercontent.com/34309957/88663679-422f4c80-d0dc-11ea-9e66-6727ef14687d.png)

Door Wil Lambo is dat als volgt verwoord:
Op 13 juli jl. kwam de vraag aan de orde of een buisleiding met waterstof onder de netten met gevaarlijke inhoud valt zoals bedoeld in artikel 1 van de WIBON. Deze vraag kwam vorige week ook aan de orde in de werkgroep “herziening NEN7171”. Ik kreeg daar onder meer de actie mee om dit uit te zoeken.  
Ik kan jullie melden dat een buisleiding met waterstof onder een net met gevaarlijke inhoud valt, dus onder het thema: “buisleiding gevaarlijke inhoud”. Maar, let wel op want er gelden een paar voorwaarden!

Om te beginnen verwijst de WIBON in artikel 1 naar artikel 12.12 tweede lid van de Wet milieubeheer (WMB). In dit artikel staat dat bij of krachtens algemene maatregel van bestuur (AMvB) onder meer categorieën van buisleidingen worden aangewezen waarover het register gegevens bevat. Met register wordt hier bedoeld het Registratiebesluit externe veiligheid. Een document van dit Registratiebesluit is bijgesloten (**zie 1**).
Artikel 6 van dit Registratiebesluit stelt: _“Als categorieën van buisleidingen als bedoeld in artikel 12.12, tweede lid, van de Wet milieubeheer worden aangewezen de categorieën van buisleidingen waarop het Besluit externe veiligheid buisleidingen van toepassing is.”_ Een document van het Besluit externe veiligheid buisleidingen (Bevb) is ook bijgesloten (**zie 2**). 
Artikel 2 van het Bevb geeft aan waarop het Bevb van toepassing is en er wordt in dit artikel verwezen naar een regeling, zijnde de Regeling externe veiligheid buisleidingen, afgekort: Revb. De eerste versie van de Revb is van 30 december 2010 en deze is op 17 juni 2014 gewijzigd. Per die datum is, onder meer, waterstof onder de Revb gebracht, zie bijgevoegde pdf waarin de publicatie over dit onderwerp in de gewijzigde Revb in de Staatscourant is opgenomen (**zie 3**). Op bladzijde 5 van de toelichting van de gewijzigde Revb staat aangegeven dat waterstof onder de categorie “brandbare stoffen” valt, zie de pdf.
In een bijgevoegd document vinden jullie ook de Revb zoals die nu geldt (**zie 4**). In artikel 2 staat dat de Revb van toepassing is voor: _“buisleidingen voor brandbare stoffen met een uitwendige diameter van 70 mm of meer of een binnendiameter van 50 mm of meer en een druk van 1.600 kPa of meer;”_ 
Zoals je kunt lezen moet de betreffende buisleiding, naast bepaalde diameters, wel een druk hebben van 1.600 kPa (= 16 bar) of meer om geduid te worden onder het thema “buisleiding met gevaarlijke inhoud”. Is de druk lager dan 16 bar, dan valt de betreffende buisleiding niet onder het thema: “buisleiding met gevaarlijke inhoud”.

**Comment by herman-vandenberg** [comment]
Bijlagen bij onderzoek door Wil Lambo:
[1. Registratiebesluit externe veiligheid, BWBR0020724-geldend_van_17-07-2015_tm_heden.pdf](https://github.com/kadaster/klic-win/files/4988252/1.Registratiebesluit.externe.veiligheid.BWBR0020724-geldend_van_17-07-2015_tm_heden.pdf)
[2. Besluit externe veiligheid buisleidingen, BWBR0028265-geldend_van_31-03-2018_tm_heden.pdf](https://github.com/kadaster/klic-win/files/4988255/2.Besluit.externe.veiligheid.buisleidingen.BWBR0028265-geldend_van_31-03-2018_tm_heden.pdf)
[3. Regeling externe veiligheid buisleidingen, stcrt-2014-16955, nu met waterstof.pdf](https://github.com/kadaster/klic-win/files/4988257/3.Regeling.externe.veiligheid.buisleidingen.stcrt-2014-16955.nu.met.waterstof.pdf)
[4. Regeling externe veiligheid buisleidingen, BWBR0029356-geldend_van_01-04-2020_tm_heden.pdf](https://github.com/kadaster/klic-win/files/4988259/4.Regeling.externe.veiligheid.buisleidingen.BWBR0029356-geldend_van_01-04-2020_tm_heden.pdf)

**Comment by herman-vandenberg** [comment]
TCS 11-09-2020: momenteel: geen apart IMKL-thema gewenst, maar wel aandachtspunt voor TCS
