### ISSUE TITLE
Aanlever-API, eenduidige naamgeving bij verschillende informatiesoorten

### ISSUE THREAD

**Issue by herman-vandenberg** [kadaster/klic-win#97]
De "Aanlever-API" wordt momenteel voor het aanleveren van verschillende informatiesoorten toegepast:
- aanleveren netinformatie (centrale netbeheerder)
- aanleveren documenten (centrale netbeheerder)
- aanleveren beheerdersinformatie ( decentrale netbeheerder)

Er is echter geen eenduidigheid in de naamgeving van de attributen van het object _Aanlevering_ tussen enerzijds de API voor beheerdersinformatie:
![image](https://user-images.githubusercontent.com/34309957/87920403-6efab880-ca79-11ea-9a35-624ffa34d3d5.png)
en de API voor netinformatie en documeneten:
![image](https://user-images.githubusercontent.com/34309957/87921022-5212b500-ca7a-11ea-884b-fddddb1cd5c5.png)

In de beschrijving van de voorgestelde BMKL-wijzigingen voor de nieuwe standaard is deze verbetering wel opgenomen (zie 
[Overzicht BMKL-issues (TCS)](https://github.com/kadaster/klic-win/blob/master/Beheren%20standaarden%20KLIC/Overzicht%20BMKL-issues%20(TCS).xlsx)).
In de TCS is deze besproken en akkoord bevonden.
Het daaraan ten grondslag liggende issue is hiermee ook vastgelegd.

**Comment by JustinRoodenburg** [comment]
**Toelichting op implementatie van het Kadaster**:
De wijzigingen zoals hierboven genoemd zijn doorgevoerd op de BMKL-API versie 2.1.
Betreft wijzigingen voor zowel Centrale als Decentrale aanleveringen.



Voor een compleet overzicht en voorbeelden van de BMKL-API versie 2.1 zie onderstaande links:
De nieuwe versie van het berichtenmodel (BMKL versie 2.1) vindt u op [deze GitHub pagina van het Kadaster](https://github.com/kadaster/klic-win/tree/master/BMKL).
Een toelichting op en en voorbeelden van de wijzigingen van de BMKL-standaarden vindt u op [deze GitHub pagina van het Kadaster](https://github.com/kadaster/klic-win/blob/master/Toekomstige%20wijzigingen/Toelichting%20specifieke%20onderwerpen/Implementatie%20upgrade%20KLIC%20standaarden/Gewijzigde%20BMKL.md).
