### ISSUE TITLE
Aanlever-API: consequenter gebruik van waarden uit waardelijsten

### ISSUE THREAD

**Issue by herman-vandenberg** [kadaster/klic-win#98]
In de API voor het object _Aanlevering_ wordt gebruik gemaakt van verschillende attributen met waarden die uit een Kadaster-KLIC waardelijst komen. Hier wordt niet altijd gebruik van gemaakt.
Het betreft met name de attributen:
- `informatieSoort`
- `aanleverStatus`
- `aanleverStapAanduiding`
- `stapStatus`
- `gradatie`

Voorstel is om daarbij consequent te verwijzen naar de betreffende waardelijsten, bijv.
"informatieSoort": "https://api.klic.kadaster.nl/waardelijsten/v2/informatieSoorten/documenten"
"aanleverStatus": "https://api.klic.kadaster.nl/waardelijsten/v2/aanleverStatussen/docTerBeoordeling"
"aanleverStapAanduiding": "https://api.klic.kadaster.nl/waardelijsten/v2/aanleverStapAanduidingen/docAanleveren
"stapStatus": "https://api.klic.kadaster.nl/waardelijsten/v2/aanleverStapStatussen/foutenGevonden"
"gradatie": "https://api.klic.kadaster.nl/waardelijsten/v2/meldingGradaties/fout"

In de beschrijving van de voorgestelde BMKL-wijzigingen voor de nieuwe standaard is deze verbetering al opgenomen (zie 
[Overzicht BMKL-issues (TCS)](https://github.com/kadaster/klic-win/blob/master/Beheren%20standaarden%20KLIC/Overzicht%20BMKL-issues%20(TCS).xlsx)). 
In de TCS is dit document besproken maar dit voorstel was nog niet expliciet gemaakt in een issue.
Deze is hiermee vastgelegd.

**Comment by herman-vandenberg** [comment]
TCS 11-09-2020: doorgesproken en akkoord; meenemen in volgende versie

**Comment by JustinRoodenburg** [comment]
**Toelichting op implementatie van het Kadaster**:
De wijzigingen zoals hierboven genoemd zijn doorgevoerd op de BMKL-API versie 2.1.

Voor een compleet overzicht van de toegestane waarden, zie de waardelijsten op:
https://api.klic.kadaster.nl/waardelijsten/v2/informatieSoorten
https://api.klic.kadaster.nl/waardelijsten/v2/aanleverStatussen
https://api.klic.kadaster.nl/waardelijsten/v2/aanleverStapAanduidingen
https://api.klic.kadaster.nl/waardelijsten/v2/aanleverStapStatussen
https://api.klic.kadaster.nl/waardelijsten/v2/meldingGradaties


Voor een compleet overzicht en voorbeelden van de BMKL-API versie 2.1 zie onderstaande links:
De nieuwe versie van het berichtenmodel (BMKL versie 2.1) vindt u op [deze GitHub pagina van het Kadaster](https://github.com/kadaster/klic-win/tree/master/BMKL).
Een toelichting op en en voorbeelden van de wijzigingen van de BMKL-standaarden vindt u op [deze GitHub pagina van het Kadaster](https://github.com/kadaster/klic-win/blob/master/Toekomstige%20wijzigingen/Toelichting%20specifieke%20onderwerpen/Implementatie%20upgrade%20KLIC%20standaarden/Gewijzigde%20BMKL.md).
